### ISSUE TITLE
Version 10.5.0

### ISSUE THREAD

**Issue by GHXST01** [ping/instagram_private_api#1]
Anyone that has experience with patching certificate pinning that wants to take a look at 10.5.0 ?
They implemented a bypass for wifi proxy settings and seem to detect a MITM.

Probably cert pinning or something of this nature but I cannot locate the functionality.
There's no files popping up with `checkClientTrusted`, `checkServerTrusted` etc.

Both fiddler and charles show _zero_, no connection attempts, _nothing_.
I don't have a wireshark setup to check for other packets, but I am positive the app is not making any connection.

In-app I am getting a network error.

**Comment by ping** [comment]
It looks like you have got your answers over at mgp25's php repo, so I'll close this.
