### ISSUE TITLE
Use cookies

### ISSUE THREAD

**Issue by ZiRonni** [ping/instagram_private_api#101]
I see in your docs of i can use cookies, but all variant show me error with pickle
[pickle data was truncated] etc

can you pleas show me example of cookies string for use in Client args

Thanks.

**Comment by ping** [comment]
@ZiRonni

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
