### ISSUE TITLE
Login with external cookie value

### ISSUE THREAD

**Issue by bagvand** [ping/instagram_private_api#102]
i have my cookie from browser 
i want use above cookie for login from your private api
pls help how do it.
tnx

**Comment by ping** [comment]
@bagvand

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
