### ISSUE TITLE
0 hits for tags beginning with Capital Letter

### ISSUE THREAD

**Issue by kaustubh-pandey** [ping/instagram_private_api#105]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Code to replicate the error must be provided below.

---

Paste the output of ``python -V`` here:

Code:

web_api = Client(auto_patch=True, drop_incompat_keys=False)
tag_feed_info = web_api.tag_feed(tag_name)
numberOfHits= tag_feed_info['data']['hashtag']['edge_hashtag_to_media']['count']
print(numberOfHits)

Error/Debug Log:
If tag_name begins with capital letter, the number of hits is always 0

**Comment by ping** [comment]
This is Instagram's limitations. You can simply do a ``tag_name.lower()``.
