### ISSUE TITLE
Upload video limits

### ISSUE THREAD

**Issue by GooG2e** [ping/instagram_private_api#107]
Hello!
I want to try to use instagram as video host because I have heard that Instagram increased video duration limit to 1.5h.
But I look at limits in this library and see that width must be smaller than 1080, size limit = 50Mb, and duration<60s
Are this limits real? Anyone tried to upload bigger videos?

Thank you very much for help!

**Comment by ping** [comment]
@GooG2e

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
