### ISSUE TITLE
If user media has multiply photos.

### ISSUE THREAD

**Issue by tesths** [ping/instagram_private_api#11]
### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I am now use **instagram_web_api**. And I follow the usage to get some body's picture.
Several months ago, Instagram publish multiply photos function.

If someone publish multiply photos. When I use web_api.user_feed, it will only get the first photos.
If I want to get the last, I will use web_api.media_info2.

I think I look for the documentation, but if users has multiply photos, users feed will not get all photos but first.

Is there any function that I can get user's all photos. Or can provide a judgment to define user post multiply photos in user_feed?

**Comment by ping** [comment]
If you're asking if it's possible for the full set of album/carousel photos to be included in user_feed for the web api, the answer is no. This is a limitation of the web api.

**Comment by tesths** [comment]
So If I want get full set of album/carousel photos, I should use Client user_feed and cycle pagination post?

**Comment by ping** [comment]
I don't really understand your question.
> So If I want get full set of album/carousel photos, I should use Client user_feed and cycle pagination post?

In a user feed, if a post has ``__typename`` as ``GraphSidecar``, it is an album post. You can then check media_info2.

```json
{
    "__typename": "GraphSidecar",
     "id": "1498202495989370732_25025320",
     "code": "BTKrzt3DM9s",
     ...
}
```

**Comment by tesths** [comment]
I think I know how to operate it😃
Sorry for my poor English.
And very thanks for your help!
