### ISSUE TITLE
get number of followers/followees

### ISSUE THREAD

**Issue by muh-bazm** [ping/instagram_private_api#110]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

When using "user_followers()" method to get list of all followers of a sample account, only a limited number of them are returned (for example 200 in following example). Is there any way to get all of them?

followers_list = temp_api.user_followers( '1713270648', rank_token = temp_api.generate_uuid() )
print( followers_list.keys() )
print( len( followers_list['users'] ) )

**Comment by notcammy** [comment]
`user_followers` allows pagination, not sure if [this example](https://github.com/ping/instagram_private_api/blob/526f244bae18962b5777e1f2f870699c0e4a8d2d/examples/pagination.py) is still up-to-date but it should point you in the right direction

**Comment by muh-bazm** [comment]
@notcammy @nemec  Thank you very much for your help. Sorry for late response.

**Comment by njsa04** [comment]
follow-on to this question: I'm trying to use the query='username' parameter to search for a follower.
It seems to only match if the user is in the current page.  
The json returned doesn't contain any paging info, so my question is, is it possible to search for a specific user using this query= parameter?  Or do you have to loop thru the pages and search for it that way?

**Comment by wlerin** [comment]
@njsa04 If that is true the problem is on instagram's end. This library doesn't do anything special with the query parameter, just sends it off to instagram directly, and returns the response.

**Comment by njsa04** [comment]
@wlerin correct - I was hoping someone might have insight into how to effectively perform the search across the set of followers - similar to the in app experience.

**Comment by ping** [comment]
@njsa04 The query parameter seem to work just fine for me when searching.

```python
    rank_token = api.generate_uuid()
    poi = 'somebody_you_know'
    results = api.user_followers(1234566789, rank_token, query=poi)
    for u in results.get('users', []):
        if u['username'] == poi:
            print(u['username'])
```

Without actual code that is showing the behavior you described, there's nothing I can suggest.

**Comment by jhart056** [comment]
@notcammy Could you please provide some sample code for that 3 second delay? I am trying to implement it but I don't know exactly where to throw it. Thanks!

What I have so far (pulled from the example):

user_id = '2958144170'
followers = []
results = api.user_followers(user_id, rank1)
#Creates list of 5000 followers
followers.extend(results.get('users', []))
next_max_id = results.get('next_max_id')
while next_max_id:
    results = api.user_followers(user_id, rank1, max_id=next_max_id)
    followers.extend(results.get('users', []))
    if len(followers) >= 5000:       # get only first 600 or so
        break
next_max_id = results.get('next_max_id')

**Comment by dvingerh** [comment]
@jhart056 You put it in the while loop and may use `sleep()` method from the `time` module
https://docs.python.org/3/library/time.html#time.sleep
