### ISSUE TITLE
Add finding username from userID

### ISSUE THREAD

**Issue by Painkiller1991** [ping/instagram_private_api#111]
it is easy to add like this post https://stackoverflow.com/questions/45332196/how-to-get-instagram-username-from-username-id-without-api-in-python

thanks a lot

**Comment by ping** [comment]
@Painkiller1991

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
