### ISSUE TITLE
checkpoint_required error

### ISSUE THREAD

**Issue by nimamahmoudi** [ping/instagram_private_api#112]
Hi,

I wrote an application based on this library. But since last week, all the accounts using this scenario have been disabled and I keep getting the checkpoint_error and get notified on the app for suspicious activity. How do I handle this problem?
Do you have a code example that handles this?

Thanks

**Comment by ping** [comment]
@nimamahmoudi

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by notcammy** [comment]
See https://github.com/ping/instagram_private_api/issues/44#issuecomment-354938425 and https://github.com/ping/instagram_private_api/issues/91#issuecomment-406982208.

Your best bet is to create a new account on the same device / IP Address / location the application is used at.

**Comment by deounix** [comment]
I'm also facing this problem. best thing I found to use web_api with fake_user_agent generator. Also I created register function so I register and login from the same ip + useragent. then I save session and re-use it again and every thing work good.
