### ISSUE TITLE
Caption not posted when deployed on server

### ISSUE THREAD

**Issue by alexiskattan** [ping/instagram_private_api#113]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

The caption on a post appears when testing locally, but when the code is deployed to the server (AWS) the photo gets posted but the caption ins't there.

---
Code:

```python
# Example code that will produce the error reported
photo_data, photo_size = media.prepare_image(
	'test.jpg', 
	aspect_ratios=MediaRatios.standard
)
api.post_photo(photo_data, photo_size, caption="test caption")

```

Is there something else that could be going on?  Is instagram IP blocking only the captions but not the images?

**Comment by maxw** [comment]
I'm seeing the same issue on AWS

**Comment by maxw** [comment]
Confirmed on google cloud too :(

**Comment by maxw** [comment]
Actually, it looks like that part of the API is broken now. I've tried from my local IP and with a fresh instagram account. No captions at all :(

**Comment by deounix** [comment]
@maxw did u find fix of this ?

**Comment by maxw** [comment]
Nope :(

**Comment by ping** [comment]
This is due to your account / access location (IP) being soft-blocked.
