### ISSUE TITLE
Can't post photo with web api

### ISSUE THREAD

**Issue by deounix** [ping/instagram_private_api#118]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Can't post photo with web api always showing to me : 

`HTTPError "Bad Request" while opening https://www.instagram.com/create/configure/`

But the photo upload working 100% cuz I'm getting upload id

in post_photo function : 

```
        try:
            res = self.opener.open(req, timeout=self.timeout)
            response_content = self._read_response(res)

            self.logger.debug('RESPONSE: {0!s}'.format(response_content))
            upload_res = json.loads(response_content)
            if upload_res.get('status', '') != 'ok':
                raise ClientError('Upload status: {}'.format(upload_res.get('status', '')))
            upload_id = upload_res['upload_id']

            print upload_id
```
and it's printing the upload id the error happened here :

```
            del headers['Content-Length']
            endpoint = 'https://www.instagram.com/create/configure/'
            res = self._make_request(
                endpoint, headers=headers,
                params={'upload_id': upload_id, 'caption': caption},
                get_method=lambda: 'POST')
            return res
```
in _make_request function.

---

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
```
from instagram_web_api import Client

web_api = Client(username="xxxx", password="xxxxx")
web_api.login()

web_api.post_photo(open("1.jpg", "rb").read(), caption="hi there")

```
```

Error/Debug Log:

`HTTPError "Bad Request" while opening https://www.instagram.com/create/configure/`

**Comment by ping** [comment]
I cannot replicate this error. I was able to post a photo with no problems.

```python
web_api = Client(username='x', password='x', authenticate=True)
with open('example.jpg', 'r') as file_data:
    file_contents = file_data.read()
    results = web_api.post_photo(file_contents, caption='This is a test')
    print(json.dumps(results, indent=2))
```
