### ISSUE TITLE
API Polling Rate Limit

### ISSUE THREAD

**Issue by bryan** [ping/instagram_private_api#12]
### Which client are you using?
- [x] app (``instagram_private_api/``)

### Purpose of your issue?
- [x] Question

---

### Describe your issue

I suppose this is a general question on how often I can make a request using the API, but for my scenario, I'm trying to view the live stream when the user starts streaming, but push notifications from mobile devices don't exist in API calls and thus it is quite difficult to know when a user is live streaming without polling `reels_tray`and checking the broadcast parameter. 

Since I don't think I've read anything about rate-limits and polling in the documents and have a few questions in mind:

- What would be a safe range (in seconds) to check reels_tray to catch the livestream in time? 
- In addition, should I randomly choose a time between two numbers to check so that it doesn't seem suspicious? (i.e. checking rand(10, 20) versus every 10 seconds)
- Is subscription possible via the API?

Thanks for your work and help in advance.

**Comment by ping** [comment]
> What would be a safe range (in seconds) to check reels_tray to catch the livestream in time?

I will not go below 2 seconds between consecutive api calls.

> In addition, should I randomly choose a time between two numbers to check so that it doesn't seem suspicious? (i.e. checking rand(10, 20) versus every 10 seconds)

It probably wouldn't hurt to do that.

> Is subscription possible via the API?

Yes, but not with this lib. I have no intention of implementing this in the foreseeable future, but PRs are welcomed.

**Comment by bryan** [comment]
I got a followup question:

- Would polling **indefinitely** as long as it doesn't go below 2 second consecutive api calls be problematic?

I appreciate the quick reply and answers. I will submit a PR if I do get around to fiddling with subscriptions. Thanks!

**Comment by ping** [comment]
The general rule of thumb is, the greater you deviate from a "regular" user's behavior, the greater the risk of getting into trouble with IG.

The short answer is, I don't and can't know for sure. You need to do your own testing. Use the longest interval that is sufficient for your needs and not the shortest interval you think you can get away with. Be reasonable. Don't be spammy/abusive.

Do review [contributing.md](https://github.com/ping/instagram_private_api/blob/master/CONTRIBUTING.md) if you intend to work on subscriptions.

**Comment by bryan** [comment]
I'll be conservative with my usage and will report if I hit a limit in case it might aid future developers hoping to achieve a similar result.

Thanks again for the help!
