### ISSUE TITLE
MUTE after follow.

### ISSUE THREAD

**Issue by sionking** [ping/instagram_private_api#122]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the lastest version v1.5.7
- [ ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x ] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Can I use this repo to do a **mute** for a user I follow ? Or to make a follow than mute.
What is the suggested option?

**Comment by wlerin** [comment]
I don't think muting is implemented yet.

**Comment by ping** [comment]
Mute is indeed not implemented.

**Comment by CB-1995** [comment]
I don't use github nor know how to make pull requests, but if you add this method to endpoints/friendships you will be able to mute.

```
def mute_unmute(self, user_id, option = 'mute', media = 'both'):

        endpoint = 'friendships/{}_posts_or_story_from_follow/'.format(option.lower())

        data = {
                '_uuid': self.uuid,
                '_uid': self.authenticated_user_id,
                '_csrftoken': self.csrftoken,
                }

        if media.lower() == 'post':
            data['target_posts_author_id'] = str(user_id)
        elif media.lower() == 'story':
            data['target_reel_author_id'] = str(user_id)
        elif media.lower() == 'both':
            data['target_posts_author_id'] = str(user_id)
            data['target_reel_author_id'] = str(user_id)

        res = self._call_api(endpoint, data)
        
        return res
```

**Comment by javad94** [comment]
Thanks to @CB-1995's code, you can use his function without editing this library's files by adding below class on top of your script right after importing this library and use mute method normally like other methods.
```python
try:
    from instagram_private_api import (
        Client, ClientError, ClientLoginError,
        ClientCookieExpiredError, ClientLoginRequiredError,
        __version__ as client_version)
except ImportError:
    import sys
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    from instagram_private_api import (
        Client, ClientError, ClientLoginError,
        ClientCookieExpiredError, ClientLoginRequiredError,
        __version__ as client_version)

class Client(Client):
    def mute_unmute(self, user_id, option = 'mute', media = 'both'):
        endpoint = 'friendships/{}_posts_or_story_from_follow/'.format(option.lower())
        data = {
                '_uuid': self.uuid,
                '_uid': self.authenticated_user_id,
                '_csrftoken': self.csrftoken,
                }
        if media.lower() == 'post':
            data['target_posts_author_id'] = str(user_id)
        elif media.lower() == 'story':
            data['target_reel_author_id'] = str(user_id)
        elif media.lower() == 'both':
            data['target_posts_author_id'] = str(user_id)
            data['target_reel_author_id'] = str(user_id)
        res = self._call_api(endpoint, data)
        return res
```

**Comment by ariamousavi945** [comment]
how about getting muted list? is there any api??
