### ISSUE TITLE
Can't like post

### ISSUE THREAD

**Issue by Smeilz** [ping/instagram_private_api#123]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [ ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Code to replicate the error must be provided below.

---

Paste the output of ``python -V`` here:

Code:

from instagram_private_api import *
import sys

user_name = 'user'
password = 'pass'

api = Client(user_name, password)
results = api.feed_timeline()
items = [item for item in results.get('feed_items', [])
         if item.get('media_or_ad')]
for item in items:
    # Manually patch the entity to match the public api as closely as possible, optional
    # To automatically patch entities, initialise the Client with auto_patch=True
    ClientCompatPatch.media(item['media_or_ad'])
    print(item['media_or_ad']['code'])
try:
    
    cc = api.media_likers('BqO5l1VDgyz')
    print(cc)
except:
    print('error', sys.exc_info())

---------------------------
What to do?

Error/Debug Log:

error (, ClientError('Bad Request: Sorry, this photo has been deleted.'), )

**Comment by Smeilz** [comment]
from instagram_private_api import *
import sys

user_name = 'user'
password = 'pass'

api = Client(user_name, password)
results = api.feed_timeline()
items = [item for item in results.get('feed_items', [])
         if item.get('media_or_ad')]
for item in items:
    # Manually patch the entity to match the public api as closely as possible, optional
    # To automatically patch entities, initialise the Client with auto_patch=True
    ClientCompatPatch.media(item['media_or_ad'])
    print(item['media_or_ad']['code'])
try:
    
    cc = api.media_likers('BqO5l1VDgyz')
    print(cc)
except:
    print('error', sys.exc_info())

And i always see this error:
error (, ClientError('Bad Request: Sorry, this photo has been deleted.'), )

---------------------------
What to do?

**Comment by ping** [comment]
You should be using a valid media ID not the media shortcode.
