### ISSUE TITLE
Upload from Gallery to DM

### ISSUE THREAD

**Issue by CoderzNation** [ping/instagram_private_api#125]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the lastest version v1.5.7
- [X] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [X] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [X] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Feature Request:

I couldn't find a function to upload a photo to a DM through "gallery". Is there any specific way to do that?

**Comment by ping** [comment]
https://instagram-private-api.readthedocs.io/en/latest/faq.html#how-to-direct-message-share
