### ISSUE TITLE
Can I renewal cookie automatically?

### ISSUE THREAD

**Issue by tbaram2** [ping/instagram_private_api#127]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [ o] Updated to the lastest version v1.5.7
- [o ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ o] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [o ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [o ] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Hello.

Thanks to you, I really enjoy Studying Instagram API.

About 3 months ago, I modified  some function of your Sources and  it has been working really well so far.

But I got a small problem about cookie.

According to your Sources , cookie remains just for 3 months after first login successly.

In my case, next week, some cookies of Clients will be expire. (So far program can re-login by using cookie file without ID and password perfectly because cookie didn't expire)

Of course, even though  after expire of cookie, program will re-login by using ID and Password and program will make new cookie file.(Because I didn't change the password of accounts,)

I was wondering that is there some way that program renewals cookie expiring date whenever re-login by using exist cookie files?

If there is no way, I have to login every 3 months by using id and passowrd  or I have to delete exist cookie file to make new cookie(new expire date) file.

Thank you.

**Comment by wlerin** [comment]
Your program just needs to save the new cookie when it re-logs in, the same way you saved it the first time (e.g. [like this](https://github.com/ping/instagram_private_api/blob/master/examples/savesettings_logincallback.py)). This isn't something the API can do for you.
