### ISSUE TITLE
Update README for usage of private API

### ISSUE THREAD

**Issue by td391** [ping/instagram_private_api#13]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

The example of usage of the private API in the [README](https://github.com/ping/instagram_private_api/blob/master/README.md)  does not work. The dictionary `results` returned by `api.feed_timeline()` seems to have been updated.
The following changes in [README](https://github.com/ping/instagram_private_api/blob/master/README.md)  should work:

```diff
@@ -73,11 +73,11 @@ password = 'YOUR_PASSWORD'
 
 api = Client(user_name, password)
 results = api.feed_timeline()
-items = results.get('items', [])
+items = results.get('feed_items', [])
 for item in items:
     # Manually patch the entity to match the public api as closely as possible, optional
     # To automatically patch entities, initialise the Client with auto_patch=True
-    ClientCompatPatch.media(item)
+    media = ClientCompatPatch.media(item['media_or_ad'])
     print(media['code'])
```

**Comment by ping** [comment]
Thanks.
