### ISSUE TITLE
implement current follow requests in the web version

### ISSUE THREAD

**Issue by javad94** [ping/instagram_private_api#132]
---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe your Feature Request:

Is there any plan to implement [Current follow requests](https://www.instagram.com/accounts/access_tool/current_follow_requests) feature which is available in the web version and gives a list of users that I requested to follow?

**Comment by wlerin** [comment]
Is that not what `friendships_pending` (in the private api) does?

**Comment by javad94** [comment]
@wlerin 
No, `friendships_pending` list **input requests** (list of other users that requested to access my private private profile) but what I want is **output requests** (requests that i made to access other users' private profile).

**Comment by Suleman-Elahi** [comment]
Its not in the app api as well !!

**Comment by javad94** [comment]
@Suleman-Elahi I think the app API doesn't have this feature because this option is not available on Instagram app.

**Comment by Suleman-Elahi** [comment]
Actually it is available in the Android and iOS app as well. You go to Settings > Account data > Connections > Current Follow requests

**Comment by javad94** [comment]
@Suleman-Elahi You are right but I think Instagram using web API cookies for this option on setting menu.

**Comment by Suleman-Elahi** [comment]
In the web api if we can do something like `request.get("https://www.instagram.com/accounts/access_tool/current_follow_requests")` then it can be implemented. I have analyzed the page source and found that the people you have sent follow requests are in inside `<script type="text/javascript">window._sharedData =` tag in JSON format.

**Comment by javad94** [comment]
@Suleman-Elahi Yeah I wrote a script for that, but when cookies expire, I need to get new cookies from the website. Because of that, I wanted this feature to be added to this library.

**Comment by wlerin** [comment]
> @Suleman-Elahi Yeah I wrote a script for that, but when the cookies expire, I need to get new cookies from the website. Because of that, I wanted this feature to be added to this library.

Do you even need to fetch cookies manually? I don't use the web api, but it looks like it has the same ability as the app api to login using your username and password whenever the cookies expire, and save those cookies using a user-supplied on_login callback function.

**Comment by ping** [comment]
It appears that the current follow requests is not retrievable via the web graphql endpoint.
And I'm not keen to implement this via scraping so I'm afraid this is a wontfix.

**Comment by javad94** [comment]
> It appears that the current follow requests is not retrievable via the web graphql endpoint.
> And I'm not keen to implement this via scraping so I'm afraid this is a wontfix.

You don't need any scraping, it has an endpoint already which gives a response in JSON.

```
import requests

headers = {
    'cookie': COOKIE,
    'dnt': '1',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9,fa;q=0.8',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
    'accept': '*/*',
    'referer': 'https://www.instagram.com/accounts/access_tool/current_follow_requests',
    'authority': 'www.instagram.com',
    'x-requested-with': 'XMLHttpRequest',
}

params = (
    ('__a', '1'),
)

response = requests.get('https://www.instagram.com/accounts/access_tool/current_follow_requests', headers=headers, params=params)
```

**Comment by Suleman-Elahi** [comment]
Leave it. I don't think it will work. The only option to get all the handles from the "current follow requests" is through scraping !!!

**Comment by javad94** [comment]
> Leave it. I don't think it will work. The only option to get all the handles from the "current follow requests" is through scraping !!!

Nope. Just add the cursor to params argument to get all handles. I tested and it's work. like:
```
import requests

headers = {
    'cookie': COOKIE,
    'dnt': '1',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9,fa;q=0.8',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
    'accept': '*/*',
    'referer': 'https://www.instagram.com/accounts/access_tool/current_follow_requests',
    'authority': 'www.instagram.com',
    'x-requested-with': 'XMLHttpRequest',
}

params = (
    ('__a', '1'),
    ('cursor', 'QVFDZHN0S1ZyWThMTW5WRFBQendSOC1zRVNNb3NXU2dfUktNYm5SZkVJYkdhMGUwX0hUQXRCRjdUTVRMamVQZHY0ZUh2X1V4SEZCcEVGMm43ZmxKREdKbg=='),
)

response = requests.get('https://www.instagram.com/accounts/access_tool/current_follow_requests', headers=headers, params=params)
```

**Comment by hdemarco** [comment]
Endpoint is https://i.instagram.com/accounts/access_tool/current_follow_requests/
**cursor** is pagination

**Comment by Suleman-Elahi** [comment]
https://github.com/Suleman-Elahi/FollowRequestsRemover

Created a standalone desktop app for this..... enjoy :)
