### ISSUE TITLE
Following activity (news) more than 30 news

### ISSUE THREAD

**Issue by karambaq** [ping/instagram_private_api#133]
---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

When I call `api.news()` it returns only 25-30 last news from following activity tab, is it possible to retrieve more, like in mobile app? In mobile app it scrolls till 4w ago activity.

**Comment by ping** [comment]
Have you actually reviewed the examples?

https://github.com/ping/instagram_private_api/blob/816c4945f80fcd64e69dd27b5e8e0df768c0f9c1/examples/pagination.py#L37-L48

**Comment by karambaq** [comment]
@ping Please answer me, I reviewed all examples before opening this issue, it's just don't work for news()

**Comment by wlerin** [comment]
The news endpoint needs a kwargs parameter.
https://github.com/ping/instagram_private_api/blob/master/instagram_private_api/endpoints/misc.py#L70

I'm not in a position to test it right now, but you could try forking the project and modifying `instagram_private_api/endpoints/misc` yourself so the news method is as follows: 

```python
    def news(self, **kwargs):
        """
        Get news feed of accounts the logged in account is following.
        This returns the items in the 'Following' tab.
        """
        return self._call_api('news/', query=kwargs)```

**Comment by karambaq** [comment]
@wlerin 
Thank you a lot!
