### ISSUE TITLE
End Cursor

### ISSUE THREAD

**Issue by OrionSJB** [ping/instagram_private_api#135]
Helllo. How can i get all comments using the max_id, with the web_api? Thank you!

**Comment by ping** [comment]
@OrionSJB

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
