### ISSUE TITLE
Problems while getting full list of user's followers

### ISSUE THREAD

**Issue by den94ka** [ping/instagram_private_api#137]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Hello.
I have problems with getting full list of user's followers. So, I tried to do it like this:
```python
def get_all_followers(self, api, user_id):
        followers = []
        rank = api.generate_uuid()
        results = api.user_followers(user_id, rank)
        next_max_id = results.get('next_max_id')

        while next_max_id:
            results = api.user_followers(user_id, rank_token=rank, max_id=next_max_id)
            followers.extend(results.get('users', []))
            next_max_id = results.get('next_max_id')
        followers.extend(results.get('users', []))
        followers.sort(key=lambda x: x['pk'])
        return followers
```

But it doesn't work right. For example, account: instagram.com/fatcoef/ has 1745 followers, but by my script I am getting only 1579 followers.

So, I tried to catch the count of users which I got after every request. So, here is the results:
1# query - 194 users
2# query - 194 users
3# query - 197 users
4# query - 195 users
5# query - 197 users
6# query - 196 users
7# query - 162 users
8# query - 35 users
9# query - 135 users
10# query - 9 users
11# query - 7 users
12# query - 8 users
13# query - 25 users

What I did wrong?

**Comment by wlerin** [comment]
You aren't saving the first 200

**Comment by francescofact** [comment]
hi, 
i was trying to do the same thing, but same thing is happening.
I always get 3 follower less then the real number. What's wrong? 

`def getMyFollowers():
		user_id = api.authenticated_user_id
		followers = []
		rank = api.generate_uuid()
		results = api.user_followers(user_id, rank)
		next_max_id = results.get('next_max_id')

		while next_max_id:
			results = api.user_followers(user_id, rank_token=rank, max_id=next_max_id)
			followers.extend(results.get('users', []))
			next_max_id = results.get('next_max_id')
		followers.extend(results.get('users', []))
		
		return followers
`

**Comment by arfathyahiya** [comment]
> 
> ## Please follow the guide below
> 
>     * Issues submitted without this template format will be **ignored**.
> 
>     * Rlease read them **carefully** and answer completely.
> 
>     * Do not post screenshots of error messages or code.
> 
>     * Put an `x` into all the boxes [ ] relevant to your issue (==> [x] _no_ spaces).
> 
>     * Use the _Preview_ tab to see how your issue will actually look like.
> 
>     * Issues about reverse engineering is out of scope and will be closed without response.
> 
>     * Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.
> 
> 
> ### Before submitting an issue, make sure you have:
> 
>     * [x]  Updated to the lastest version v1.5.7
> 
>     * [x]  Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
> 
>     * [x]  [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
> 
>     * [x]  Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)
> 
> 
> ### Which client are you using?
> 
>     * [x]  app (`instagram_private_api/`)
> 
>     * [ ]  web (`instagram_web_api/`)
> 
> 
> ### Describe your Question/Issue:
> 
> Please make sure the description is worded well enough to be understood with as much context and examples as possible.
> 
> Hello.
> I have problems with getting full list of user's followers. So, I tried to do it like this:
> 
> ```python
> def get_all_followers(self, api, user_id):
>         followers = []
>         rank = api.generate_uuid()
>         results = api.user_followers(user_id, rank)
>         next_max_id = results.get('next_max_id')
> 
>         while next_max_id:
>             results = api.user_followers(user_id, rank_token=rank, max_id=next_max_id)
>             followers.extend(results.get('users', []))
>             next_max_id = results.get('next_max_id')
>         followers.extend(results.get('users', []))
>         followers.sort(key=lambda x: x['pk'])
>         return followers
> ```
> 
> But it doesn't work right. For example, account: instagram.com/fatcoef/ has 1745 followers, but by my script I am getting only 1579 followers.
> 
> So, I tried to catch the count of users which I got after every request. So, here is the results:
> 1# query - 194 users
> 2# query - 194 users
> 3# query - 197 users
> 4# query - 195 users
> 5# query - 197 users
> 6# query - 196 users
> 7# query - 162 users
> 8# query - 35 users
> 9# query - 135 users
> 10# query - 9 users
> 11# query - 7 users
> 12# query - 8 users
> 13# query - 25 users
> 
> What I did wrong?

You missed the first ~200 users when getting `next_max_id` before while loop

**Comment by wlerin** [comment]
@francescofact 

> hi,
> i was trying to do the same thing, but same thing is happening.
> I always get 3 follower less then the real number. What's wrong?

as @arfathyahiya correctly points out, the code in the original issue as well as your sample code calls `api.user_followers` twice before it begins storing the results in `followers`, discarding the users returned in the first call. This should be causing you to have way more than three followers missing, though.

**Comment by nfarooq17** [comment]
> @francescofact
> 
> > hi,
> > i was trying to do the same thing, but same thing is happening.
> > I always get 3 follower less then the real number. What's wrong?
> 
> as @arfathyahiya correctly points out, the code in the original issue as well as your sample code calls `api.user_followers` twice before it begins storing the results in `followers`, discarding the users returned in the first call. This should be causing you to have way more than three followers missing, though.

@wlerin 
const followingFeed = ig.feed.accountFollowing(req.body.pk)
 do {
        let flwngs = await followingFeed.items()
        following.push(...flwngs)
        console.log(following.length)
        await Bluebird.delay(2000)
    } while (followingFeed.isMoreAvailable())
    
    I am still getting less followers and following was well around 300, can you please guide me what is the problem with my code.

**Comment by wlerin** [comment]
That's using neither python nor this library so I have no idea.

edit: Perhaps ask over here: https://github.com/dilame/instagram-private-api
