### ISSUE TITLE
Some tests from tests\test_private_api.py FAILED

### ISSUE THREAD

**Issue by gregkr** [ping/instagram_private_api#138]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:
I try to run tests and see errors.

---

Paste the output of ``python -V`` here:
python -V
Python 3.6.0

Code:
```
D:\....\instagram_private_api>python -m tests.test_private_api -settings settings.txt -u mil****2 -p Go****0
Client version: 1.5.7
```

Error/Debug Log:

```python
======================================================================
ERROR: test_post_video_mock (tests.private.upload.UploadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\....\instagram_private_api\tests\private\upload.py", line 699, in test_post_video_mock
    with open(sample_video, 'rb') as video_fp, \
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\....\\instagram_private_api\\tests\\private\\../media/test.mp4'

======================================================================
ERROR: test_search_users (tests.private.users.UsersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\....\instagram_private_api\tests\private\users.py", line 89, in test_search_users
    results = self.api.search_users('maruhanamogu', rank_token)
TypeError: search_users() takes 2 positional arguments but 3 were given

======================================================================
FAIL: test_collection_feed (tests.private.collections.CollectionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\....\instagram_private_api\tests\private\collections.py", line 47, in test_collection_feed
    self.assertTrue(results.get('items'), 'No collection')
AssertionError: [] is not true : No collection

======================================================================
FAIL: test_self_feed (tests.private.feed.FeedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\....\instagram_private_api\tests\private\feed.py", line 103, in test_self_feed
    self.assertGreater(len(results.get('items', [])), 0, 'No items returned.')
AssertionError: 0 not greater than 0 : No items returned.

======================================================================
FAIL: test_stories_archive (tests.private.highlights.HighlightsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\....\instagram_private_api\tests\private\highlights.py", line 39, in test_stories_archive
    self.assertIn('items', results)
AssertionError: 'items' not found in {'reel_auto_archive': 'unset', 'status': 'ok'}

----------------------------------------------------------------------
Ran 203 tests in 296.861s

FAILED (failures=3, errors=2, skipped=40)

```

What am I wrong ?

**Comment by wlerin** [comment]
First test can't succeed as the test video isn't included in the repo. I don't think including it is a good idea, so you either need to just ignore that one or supply your own properly formatted video.

search_users was [updated 5 days ago](https://github.com/ping/instagram_private_api/commit/6f93875bcffddf071a74d7ee9ccf698e1f4b0de0) and all arguments besides query were moved to kwargs. This test needs to be updated.

For the others I'd guess the results in the tests depend on ping's test account, and yours differs (e.g. it no collections or posts.)

**Comment by gregkr** [comment]
Thank you for reply. But what about this?

`D:\....\instagram_private_api\instagram_private_api\client.py:172: UserWarning: Proxy support is alpha
.
  warnings.warn('Proxy support is alpha.', UserWarning)
Exception: 'HTTPError' object has no attribute 'reason' `

**Comment by ping** [comment]
Which test is throwing that error?

**Comment by gregkr** [comment]
This is not a test, but what does it change? 
I use the library. Error inside the library. 
What's wrong?
PS: I use instagram_private_api for connect IG by proxy.

**Comment by ping** [comment]
That is a different problem. This issue is about failing tests. Please submit a new issue with the required technical info (code to reproduce the error, full error stack, etc.)
