### ISSUE TITLE
Exception: 'HTTPError' object has no attribute 'reason'

### ISSUE THREAD

**Issue by gregkr** [ping/instagram_private_api#140]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Paste the output of ``python -V`` here: Python 2.7

Code:

```
try:
    from instagram_private_api import (
        Client, ClientError, ClientLoginError,
        ClientCookieExpiredError, ClientLoginRequiredError,
        __version__ as client_version)
except ImportError:
    import sys
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    from instagram_private_api import (
        Client, ClientError, ClientLoginError,
        ClientCookieExpiredError, ClientLoginRequiredError,
        __version__ as client_version)

try:
    from urllib.request import urlopen, build_opener, install_opener, ProxyHandler # Python 3
except ImportError:
    from urllib2 import urlopen, build_opener, install_opener, ProxyHandler # Python 2

class IgClient
    def __init__(self, ...):
        ....
        self.creation_result = self.login()
        ....
    def login(self):
        try :
            self.proxy_handler = ProxyHandler( { "https" : "https://%s" % ( self.proxy_addr_port) } )
            self.client = Client( self.user_name, self.password, on_login=lambda x: onlogin_callback(x, self.settings_file), proxy_handler=self.proxy_handler)
         except Exception as e:
            print('Exception: {0!s}'.format(e))
```

Error/Debug Log:

```python
Exception: 'HTTPError' object has no attribute 'reason'
```

**Comment by wlerin** [comment]
Please raise the full error with traceback and include it here (simplest way: remove the try and except statements). 

I can't see why this should be happening as both the 2.7 and 3.2+ HTTPError classes have a `reason` attribute (that's just an alias property for msg).

**Comment by gregkr** [comment]
This is a full error with traceback after try-except statements removed:

```
D:\....\debug>python py\igclient.py
Traceback (most recent call last):
  File "py\igclient.py", line 294, in <module>
    ig_test4()
  File "py\igclient.py", line 283, in ig_test4
    igc = IgClient('m....02','Go....20', 'credentials/m....2_credentials.json', '9..2..2..1.:4.', '')
  File "py\igclient.py", line 55, in __init__
    self.creation_result = self.login()
  File "py\igclient.py", line 61, in login
    self.client = Client( self.user_name, self.password, on_login=lambda x: onlogin_callback(x, self.settings_file),
proxy_handler=self.proxy_handler)
  File "D:\....\instagram_private_api\instagram_private_api\client.py", line 208, in __init__
    self.login()
  File "D:\....\instagram_private_api\instagram_private_api\endpoints\accounts.py", line 50, in login
    'accounts/login/', params=login_params, return_response=True)
  File "D:\....\instagram_private_api\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "D:\....\instagram_private_api\instagram_private_api\errors.py", line 105, in process
    error_msg = http_error.reason
AttributeError: 'HTTPError' object has no attribute 'reason'

D:\....\debug>python -V
Python 2.7

```
PS: I use Python 2.7 in project Qt 5.6.3 through including to qt project file next statements:
`
INCLUDEPATH += D:/Python27/include
LIBS += -LD:/Python27/libs -lm -lpython27 -lpthread
`

**Comment by ping** [comment]
Your version of Python 2.7 is too old, ``HTTPError.reason`` was introduced from 2.7.4 (April 2013).
Upgrading your Python version to a more recent one should solve the problem.

**Comment by gregkr** [comment]
Thank you very much. Version upgrade really solved the problem.
