### ISSUE TITLE
module_view not working as expected

### ISSUE THREAD

**Issue by ranjbarhadi** [ping/instagram_private_api#141]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

I was trying to update view count for a media. it looks like that like and view have the same endpoints. As I understand passing the module name `video_view` should update the view count of a media instead of its like count. so I tried it and it only liked the media instead of updating the view count.

---

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_private_api import Client, ClientCompatPatch

user_name = '---------'
password = '----------'

api = Client(user_name, password)
results = api.post_like("1986230217740718131_5685779641", "video_view")

print(results)
```

Error/Debug Log:
there is no error. it returns `{'status':'ok'}` which is ok. but not the expected result IMHO.

**Comment by ping** [comment]
How do you make the mental jump to think that a method called ``post_like`` has anything to do video counts?

The docs, which you have supposedly read, clearly states what the method is for.

**Comment by ranjbarhadi** [comment]
Oh, attitude!

**Comment by ranjbarhadi** [comment]
do you have any idea how to do it?
