### ISSUE TITLE
DMs and 2FA

### ISSUE THREAD

**Issue by ohld** [ping/instagram_private_api#142]
Hi! Thanks for your great work!

Is there any possibility to add DMs support and the ability to add support for login with 2FA?

**Comment by ping** [comment]
@ohld

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ohld** [comment]
This is not an issue, this is a feature request. And you don't have the proper template for this type of GitHub Issues.

**Comment by notcammy** [comment]
You can submit a new feature request with the appropriate template when you create a new issue, it's [right here](https://github.com/ping/instagram_private_api/issues/new/choose)

**Comment by ohld** [comment]
Anyway, any answers on the question?

**Comment by notcammy** [comment]
The repository owner has stated a while ago that he has no intentions to implement either feature.
See https://github.com/ping/instagram_private_api/issues/49#issuecomment-364758498

**Comment by ohld** [comment]
That’s why I’m asking again - the whole year has been passed
