### ISSUE TITLE
video view

### ISSUE THREAD

**Issue by ali101110** [ping/instagram_private_api#152]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Feature Request:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

hello ping :)
would you please add video view feature to be able to view the video ?
ex : `api.video_view("media_id")`

**Comment by ping** [comment]
@ali101110

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ali101110** [comment]
> @ali101110
> 
> Your issue report does not conform to the issue template that has been specified for this repo:
> https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md
> 
> Please edit your issue to comply with the template requirement.
> 
> This issue will be closed after 24 hours if no followup action is taken.
> 
> [This comment is auto-generated. ref=notemplate]

i edited

**Comment by ali101110** [comment]
@ping
i edited

**Comment by wlerin** [comment]
What exactly are you asking for?

**Comment by ali101110** [comment]
@wlerin a feature to be able to view the media through this library

**Comment by wlerin** [comment]
That doesn't make sense. You can view the file on your hard drive using your favorite video player, or on the web once it's been uploaded, but there isn't any way for *this library* to show you the video.

**Comment by ali101110** [comment]
@wlerin i mean increasing video views

**Comment by wlerin** [comment]
Oh, whoops. Yeah sorry that makes a lot more sense.

**Comment by reliefs** [comment]
anything new about this function ?

**Comment by notcammy** [comment]
I doubt this will be implemented as it will very likely only be used by spam bots

**Comment by reliefs** [comment]
This api works with view_stories
https://github.com/instagrambot/instabot

**Comment by ping** [comment]
I have no intention of supporting this.
