### ISSUE TITLE
hi ping please contact us

### ISSUE THREAD

**Issue by goldnitro** [ping/instagram_private_api#153]
ping thanks for all the work on this.
Please contact us at admin@goldnitro.com
We'd love to chat.

**Comment by ping** [comment]
@goldnitro

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
