### ISSUE TITLE
Use API in a different language

### ISSUE THREAD

**Issue by Spixmaster** [ping/instagram_private_api#154]
I develop in C++ and am relatively familiar with that language.
Unfortunately, there isn't a API for C++.
Can I use this API with C++ either anyway? Could you tell me how?

Thanks in advance
Spixmaster

**Comment by ping** [comment]
@Spixmaster

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
