### ISSUE TITLE
byte string of the image? Wut

### ISSUE THREAD

**Issue by acujl** [ping/instagram_private_api#155]
From https://instagram-private-api.readthedocs.io/en/latest/api.html#instagram_private_api.Client.post_photo

"photo_data – byte string of the image"

You guys don't have an example for it? Can't really upload images since it's not specified how you can transform an image into a  byte string of the image..

**Comment by ping** [comment]
@acujl

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ali101110** [comment]
example : 
```
    with open("./pics/pic.jpg",'rb') as file:
        api.post_photo(file.read(),size=(1000,1000))
```

**Comment by TheFakeWater** [comment]
Hello
