### ISSUE TITLE
How to load the full liked feed?

### ISSUE THREAD

**Issue by coolnickname** [ping/instagram_private_api#16]
### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
https://github.com/ping/instagram_private_api/blob/master/README.md)%20and%20[docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

The docs showed that feed_liked() gives a list of liked posts, but near the end of the dict that is returned it says `'more_available': True/False`. In my case it says True because I guess the number of liked posts exceeds the maximum that is accepted at once. How can I load the rest? 

There is another boolean, `'auto_load_more_enabled'`, which is True in my case.

**Comment by ping** [comment]
Please update to [1.3.1](https://github.com/ping/instagram_private_api/releases/tag/1.3.1) which will support a keyword arg ``max_id`` for pagination.

You can check the pagination example for how to use it.
