### ISSUE TITLE
Is there a basic working sample?

### ISSUE THREAD

**Issue by eduardoegos** [ping/instagram_private_api#160]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

I'm not very familiar with python, so i'm having a little trouble around the api. i can get the examples to work separately , but if i try to add something else i get many many errors, is there a simple example of the things work together? like a file that makes the login using the cache, has the pagination setup and i can do simple stuff, like following somebody...

---

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

web_api = Client()
user_feed_info = web_api.user_feed('1234567890', count=10)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

**Comment by notcammy** [comment]
Without showing any actual code you've written that you are having trouble with there is nothing to suggest.

See https://github.com/ping/instagram_private_api/issues/42#issuecomment-350289893 for an example to create and reuse cookies while logging in. It's kinda old, but i think it still works.

Here's a snippet from the pagination example which shows you how to paginate through a person's followers with a max_id. 

You can get the user_id with the `username_info` method and getting the `pk` value from the json response as shown in the snippet as well.

```py
    # get user id to use later
    user_info = ig_client.username_info(user_to_check)
    user_id = user_info['user']['pk']

    followers = []
    results = api.user_followers(user_id)
    followers.extend(results.get('users', []))

    next_max_id = results.get('next_max_id')
    while next_max_id:
        results = api.user_followers(user_id, max_id=next_max_id)
        followers.extend(results.get('users', []))
        if len(followers) >= 600:       # get only first 600 or so
            break
        next_max_id = results.get('next_max_id')
```

**Comment by eduardoegos** [comment]
Hey, my apologies, i did not write much, should have posted the code anyway. your samples are really helpful,  but i'm still getting errors. i'm using your auth and views samples, in the views i'm adding a code to follow the instagram account, just as a test, like this:


def do_something():
	api = auth.login_instagram("user", "pass")
	# Do stuff with instagram_app_api
	result = api.friendships_create("instagram")
	print(result["status"])

do_something()

login goes alright, but the following part gets those errors:

Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Eduardo\downloads\api\instagram_private_api\client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views.py", line 12, in <module>
    do_something()
  File "views.py", line 9, in do_something
    result = api.friendships_create("instagram")
  File "C:\Users\Eduardo\downloads\api\instagram_private_api\endpoints\friendships.py", line 157, in friendships_create
    res = self._call_api(endpoint, params=params)
  File "C:\Users\Eduardo\downloads\api\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\Users\Eduardo\downloads\api\instagram_private_api\errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found


Can you help me as to what am i doing wrong?

**Comment by notcammy** [comment]
`friendships_create()` requires an user id as input, not an username. See the example in my previous reply to get user id.

Refer to the documentation available to check what kind of arguments each endpoint requires.

**Comment by eduardoegos** [comment]
oh, right, my bad. got it now, all working as expected. thank you very much
