### ISSUE TITLE
How to send direct message?

### ISSUE THREAD

**Issue by payanthe** [ping/instagram_private_api#161]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

How to Send Direct Message ? 

---

**Comment by r0und3r** [comment]
As stated in the documentation, there is no implementation of sending direct messages and there are no plans to do so. https://instagram-private-api.readthedocs.io/en/latest/faq.html?highlight=direct%20message#how-to-direct-message-share

**Comment by xecgr** [comment]
@ping I have a feature request about this topic. I'm able to code it (I'm already on it and it's almost working full)
Are you open to add this code to main branch?

**Comment by lorenzogiustiniani80** [comment]
@xecgr  it's great! finally a solution. Please, can you share your private direct functionality?

Thanks

**Comment by phcamargo23** [comment]
Hi @xecgr , could you send me the solution too? Thanks.

**Comment by phcamargo23** [comment]
Hello @ping , why "no plans to implement messaging or direct sharing"? Why won't you accept this PR?

**Comment by dvingerh** [comment]
Because it would be used for spam

**Comment by steffanjensen** [comment]
it can also be used to reply to messages.. come on

I made this one if someone needs it:
https://github.com/instabotai/instabotai/blob/master/examples/reply_pending_inbox.py

**Comment by steffanjensen** [comment]
There can be many reasons why dev does not want to implement this feature.. We have to respect him, he could get in legal trouble at worst case.

But there isn't really a fully working api on github because each one lack some functionality, it could be nice if we could get a "complete" package. 

If you look at his https://github.com/ping/instagram_private_api/blob/master/LICENSE there is no reason for us not to fork it and implement it our-self if we need.

**Comment by ghrlt** [comment]
For people still looking for a way of automating sending message on Instagram, checkout [Instagrapi](https://github.com/adw0rd/instagrapi).

Everything is there
