### ISSUE TITLE
Prepare and upload Image to Instagram

### ISSUE THREAD

**Issue by Luc1412** [ping/instagram_private_api#163]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

I currently try to upload an image to Instagram. When I upload the Image I get a Internal Server Error. I didn't found my mistake. I prepared the Image to 4:5 ratio, but it doesn't work.

---

Code:

```python
i = ... # Getting my Image as pillow.Image

# Adjust Ratio to 4:5 & make image smaller
def adjust_image(old_image):
    image = Image.new('RGB', (int(old_image.height * 4 / 5), old_image.height))
    image.paste(old_image, (int(image.width / 2 - old_image.width / 2), 0))
    image = image.resize((int(image.width / 2), int(image.height / 2)), Image.ANTIALIAS)
    return image

i = adjust_image(s)
api = Client('my_username', 'my_password')
with io.BytesIO() as obj:
   # Write Image in ByteIO
    s.save(obj, format="PNG")
    api.post_photo(obj.getvalue(), s.size)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "D:\MyAwsomeWorkspace\venv\lib\site-packages\discord\client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "D:/MyAwsomeWorkspace/bot.py", line 176, in on_command_error
    raise error
  File "D:\MyAwsomeWorkspace\venv\lib\site-packages\discord\ext\commands\core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\MyAwsomeWorkspace\cogs\test.py", line 36, in test
    api.post_photo(obj.getvalue(), s.size)
  File "D:\MyAwsomeWorkspace\venv\lib\site-packages\instagram_private_api\endpoints\upload.py", line 476, in post_photo
    disable_comments=disable_comments, is_sidecar=is_sidecar)
  File "D:\MyAwsomeWorkspace\venv\lib\site-packages\instagram_private_api\endpoints\upload.py", line 207, in configure
    res = self._call_api(endpoint, params=params)
  File "D:\MyAwsomeWorkspace\venv\lib\site-packages\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "D:\MyAwsomeWorkspace\venv\lib\site-packages\instagram_private_api\errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Internal Server Error: Unknown Server Error.
```

**Comment by janoroot** [comment]
So it's not possible to upload an image into the account?
