### ISSUE TITLE
media_seen() return 'ok' , but target story not marked as seen 

### ISSUE THREAD

**Issue by DresdenAlive** [ping/instagram_private_api#165]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

I'm using  media_seen() for marking story items as seen, but it's not working.
media_seen() calls 'media/seen/' but web version of Instagram calls 'https://www.instagram.com/stories/reel/seen' maybe it's a problem?

---

Code:

```python

result = api.user_reel_media('212572123')
api.media_seen(result['items'])

```

**Comment by alfonsodipace** [comment]
any update?

**Comment by coisan** [comment]
Facing the same issue...
