### ISSUE TITLE
How to save and restore cookie?

### ISSUE THREAD

**Issue by suffrage** [ping/instagram_private_api#17]

**Comment by ping** [comment]
@suffrage

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
