### ISSUE TITLE
Instagram Live Q&A

### ISSUE THREAD

**Issue by finicky** [ping/instagram_private_api#180]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Feature Request:

Save Instagram Live questions and answers.

```
    public function getLiveBroadcastQuestions(
        $broadcastId)
    {
        return $this->ig->request("live/{$broadcastId}/questions/")
            ->addParam('sources', 'story_and_live')
            ->getResponse(new Response\BroadcastQuestionsResponse());
    }
```

I tried porting [this](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Live.php) to python with not much luck.
```
    def broadcast_questions(self, broadcast_id):
        broadcast_id = str(broadcast_id)
        query = {
            'sources': 'story_and_live'
        }
        endpoint = 'live/{broadcast_id!s}/questions/'.format(**{'broadcast_id': broadcast_id})
        return self._call_api(endpoint, query=query)
```
I get a "ClientError: Internal Server Error: Invalid request" when I run the above code. Any help would be appreciated.

**Comment by ping** [comment]
> Issues about reverse engineering is out of scope and will be closed without response.
