### ISSUE TITLE
How do I change a device id?

### ISSUE THREAD

**Issue by eduardoegos** [ping/instagram_private_api#183]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

So i use the bot with a few of accounts of mine, i'm using an adaptation of a login that i found in the examples (code below), but i always get the same device with all of the accounts, i saw that there is a generate_deviceid() function with a seed argument within the Client class, but i'm not sure how to set it before connecting the Client, being that it is a class function. The code even gets the device_id when reusing auth settings, but again, not sure how to set a new id from the start.

---

Paste the output of ``python -V`` here:

Code:

```python
def login_instagram(username, password):

	print('Versão do Cliente: {0!s}'.format(client_version))
	print("Login {}".format(username))

	device_id = None
	try:

		settings_file = 'credentials/'+ username +'.json'
		if not os.path.isfile(settings_file):
			# settings file does not exist
			print('Não há arquivo de credencial: {0!s}'.format(settings_file))

			# login new
			api = Client(
				username, password,
				on_login=lambda x: onlogin_callback(x, settings_file))
		else:
			with open(settings_file) as file_data:
				cached_settings = json.load(file_data, object_hook=from_json)
			print('Reutilizando credenciais: {0!s}'.format(settings_file))

			device_id = cached_settings.get('device_id')
			# reuse auth settings
			api = Client(
				username, password,
				settings=cached_settings)

	except (ClientCookieExpiredError, ClientLoginRequiredError) as e:
		print('ClientCookieExpiredError/ClientLoginRequiredError: {0!s}'.format(e))

		# Login expired
		# Do relogin but use default ua, keys and such
		api = Client(
			username, password,
			device_id=device_id,
			on_login=lambda x: onlogin_callback(x, settings_file))

	except ClientLoginError as e:
		print('ClientLoginError {0!s}'.format(e))
	except ClientError as e:
		print('ClientError {0!s} (Code: {1:d}, Response: {2!s})'.format(e.msg, e.code, e.error_response))
	except Exception as e:
		print('Unexpected Exception: {0!s}'.format(e))

	return api
```

Error/Debug Log:

**Comment by notcammy** [comment]
Generate it before instantiating a new api object which accepts `device_id` as one of the possible arguments

There's an example right here: https://github.com/ping/instagram_private_api/blob/816c4945f80fcd64e69dd27b5e8e0df768c0f9c1/tests/test_private_api.py#L80

**Comment by eduardoegos** [comment]
amazing, thank you!!
