### ISSUE TITLE
How to see stories?

### ISSUE THREAD

**Issue by prostokak** [ping/instagram_private_api#184]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the lastest version v1.6.0
- [ ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your issue
What I've done below.

Code:

```python
reels = api.reels_media(inst_ids[:20])['reels'] # only 20 allowed_(
print(reels)
for i in reels:
    reel_id = reels[i]['items'][0]['id'] + '_' +str(reels[i]['id'])
    reel_time = str(reels[i]['latest_reel_media']) + '_' + str(reels[i]['latest_reel_media'] + 120)
    stories[reel_id] = [reel_time]

print(api.media_seen(stories)) # printed ok, but haven't seen
```
Once it worked, but mostly(

**Comment by ping** [comment]
@prostokak

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by tomquirk** [comment]
I've implemented this in my fork for the web client - will look at submitting a PR soon, but maybe try it out in the interim https://github.com/tomquirk/instagram_private_api @prostokak

**Comment by azor0** [comment]
@tomquirk I checked out your changes, but it seems not to be working.
The response is `{'status': 'ok'}`, but when I go to see if the account has watched the story of my other account, the view is not there.

Great work any case, it's amazing how people devote time to opensource projects!

**Comment by alfonsodipace** [comment]
any update for this? i need the same function :(
