### ISSUE TITLE
How to handle throttling

### ISSUE THREAD

**Issue by CssHammer** [ping/instagram_private_api#185]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

I`m wondering how to handle ClientThrottledError properly or maybe how to avoid it?

---

Paste the output of ``python -V`` here: Python 3.7.3

Code:

I try to workaround it like this but seems like it is not enough.
```python
info = api.user_info(user['pk'])['user']
time.sleep(random.randint(1, 5))
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "/Users/go/PycharmProjects/ig_test/main.py", line 42, in <module>
    info = api.user_info(user['pk'])['user']
  File "/Users/go/PycharmProjects/ig_test/venv/lib/python3.7/site-packages/instagram_private_api/endpoints/users.py", line 17, in user_info
    res = self._call_api('users/{user_id!s}/info/'.format(**{'user_id': user_id}))
  File "/Users/go/PycharmProjects/ig_test/venv/lib/python3.7/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/Users/go/PycharmProjects/ig_test/venv/lib/python3.7/site-packages/instagram_private_api/errors.py", line 118, in process
    error_response=json.dumps(error_obj))
instagram_private_api.errors.ClientThrottledError: Please wait a few minutes before you try again.
```

**Comment by callten** [comment]
If it's in a loop, catch the error with try/except and, in the except, add a longer sleep (a couple of minutes) so it waits longer before retrying.

**Comment by ping** [comment]
```instagram_private_api.errors.ClientThrottledError: Please wait a few minutes before you try again.``` is pretty clear about it.

**Comment by Miladinho** [comment]
@ping is this API subject to the same hourly request limits set in the official instagram developer api accounts?

**Comment by BahramJannesar** [comment]
I try a lot of setting for my script and finally one of them works, I set the time.sleep(600) and then I saw, every 10 min script can request 16 or sometimes 17 times, and again go to sleep for 10 min. I think "please wait a few minutes" is a True sentence about this error, as this setting per hour you can request 16*6 = 96 times and per day maybe 2304 times.
