### ISSUE TITLE
Web Api media_info, user_info, compat_media, compat_user not working

### ISSUE THREAD

**Issue by ep3p** [ping/instagram_private_api#19]
### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Python 3.6.0 :: Continuum Analytics, Inc.

---

### Describe your issue

I have run the test_web_api, I just thought to notify the issue. Sorry for the mess. vkill is right.

Client version: 1.3.2
New login.
test_search (web.client.ClientTests) ... ok
test_client_properties (web.client.ClientTests) ... ok
test_client_errors (web.client.ClientTests) ... ok
test_client_init (web.client.ClientTests) ... ok
test_login_mock (web.client.ClientTests) ... ok
test_media_info (web.media.MediaTests) ... ERROR
test_notfound_media_info (web.media.MediaTests) ... ok
test_media_comments (web.media.MediaTests) ... ok
test_notfound_media_comments (web.media.MediaTests) ... ok
test_media_comments_noextract (web.media.MediaTests) ... ok
test_post_comment (web.media.MediaTests) ... skipped 'Modifies data.'
test_post_comment_mock (web.media.MediaTests) ... ok
test_del_comment (web.media.MediaTests) ... skipped 'Modifies data / Needs actual data.'
test_del_comment_mock (web.media.MediaTests) ... ok
test_post_like (web.media.MediaTests) ... skipped 'Modifies data'
test_post_like_mock (web.media.MediaTests) ... ok
test_delete_like (web.media.MediaTests) ... skipped 'Modifies data'
test_delete_like_mock (web.media.MediaTests) ... ok
test_carousel_media_info (web.media.MediaTests) ... ok
test_post_comment_validation_mock (web.media.MediaTests) ... ok
test_user_info (web.user.UserTests) ... ERROR
test_user_feed (web.user.UserTests) ... ok
test_notfound_user_feed (web.user.UserTests) ... ok
test_user_feed_noextract (web.user.UserTests) ... ok
test_user_followers (web.user.UserTests) ... ok
test_user_followers_noextract (web.user.UserTests) ... ok
test_user_following (web.user.UserTests) ... ok
test_friendships_create (web.user.UserTests) ... skipped 'Modifies data'
test_friendships_create_mock (web.user.UserTests) ... ok
test_friendships_destroy (web.user.UserTests) ... skipped 'Modifies data'
test_friendships_destroy_mock (web.user.UserTests) ... ok
test_compat_media (web.compatpatch.CompatPatchTests) ... ERROR
test_compat_comment (web.compatpatch.CompatPatchTests) ... ok
test_compat_user (web.compatpatch.CompatPatchTests) ... ERROR
test_compat_user_list (web.compatpatch.CompatPatchTests) ... ok
test_post_photo (web.upload.UploadTests) ... skipped 'Modifies data'
test_post_photo_mock (web.upload.UploadTests) ... ok
test_tag_feed (web.feed.FeedTests) ... ok
test_location_feed (web.feed.FeedTests) ... ok

**Comment by vkill** [comment]
Instagram closed the https://www.instagram.com/query/

**Comment by suffrage** [comment]
i have same problem with user_info

**Comment by vgavro** [comment]
yup... Any ideas how to get username by user_id without public api now?

**Comment by ep3p** [comment]
I would just create an Instagram Account and use the instagram_private_api client.

**Comment by ping** [comment]
Thanks for the reports. ``user_info()`` and ``media_info()`` are now deprecated.

You may want to switch to ``media_info2()`` and ``user_info2()`` (new in [1.3.3](https://github.com/ping/instagram_private_api/releases/tag/1.3.3)). Do expect changes in the returned objects.

**Comment by metal3d** [comment]
user_info2 cannot give owner name from id, getting posts only gives owner id. That means that, at this time, it's not possible to get owner name of a post.
