### ISSUE TITLE
There is no next_max_child_cursor for a comment to get its replies

### ISSUE THREAD

**Issue by EmadHelmi** [ping/instagram_private_api#191]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

For all media comments which have replies there is no `next_max_child_cursor` for each comment.

---

Paste the output of ``python -V`` here:

Code:

```python
from instagram_private_api import (
    Client, ClientError, ClientLoginError,
    ClientCookieExpiredError, ClientLoginRequiredError, ClientCompatPatch,
    __version__ as client_version)
from pprint import pprint

# Aftre save the client in the account variable
comments = account.media_comments(media_id='2102154626643076864_1589458337')
pprint(comments['comments'][0])
```

Error/Debug Log:

```python
{'bit_flags': 0,
 'child_comment_count': 11,
 'comment_index': 0,
 'comment_like_count': 8,
 'content_type': 'comment',
 'created_at': 1564816468,
 'created_at_utc': 1564816468,
 'did_report_as_spam': False,
 'has_liked_comment': False,
 'has_more_head_child_comments': False,
 'has_more_tail_child_comments': True,
 'inline_composer_display_condition': 'never',
 'num_tail_child_comments': 11,
 'other_preview_users': [{'id': 2256505794,
                          'profile_pic_url': 'https://scontent-cdg2-1.cdninstagram.com/vp/d66084c66c4da16261540a3ac1130c4b/5DCD1EA8/t51.2885-19/s150x150/28155962_1811885372167300_3865557754236108800_n.jpg?_nc_ht=scontent-cdg2-1.cdninstagram.com'},
                         {'id': 7423552317,
                          'profile_pic_url': 'https://scontent-cdg2-1.cdninstagram.com/vp/198b28abdd6845aa5684934342bef937/5DD54C38/t51.2885-19/s150x150/40509142_266377630666331_3235558645450145792_n.jpg?_nc_ht=scontent-cdg2-1.cdninstagram.com'}],
 'pk': 17865828721443097,
 'preview_child_comments': [],
 'share_enabled': True,
 'status': 'Active',
 'text': 'الان دولت داره فقط واسه رو کم کنی با آمریکا روی دلار یارانه میده تا '
         'قیمتش رو پایین نگهداره ... پس هر کس عاقل باشه میفهمه این قیمت دلار '
         'مصنوعی هست و ارزش دلار بیشتر از این عدد هست',
 'type': 0,
 'user': {'full_name': 'm',
          'is_private': True,
          'is_verified': False,
          'latest_reel_media': 0,
          'pk': 9486442541,
          'profile_pic_id': '1929869459511984358_9486442541',
          'profile_pic_url': 'https://scontent-cdg2-1.cdninstagram.com/vp/4c8bf9895f7dd7e46c1a8333d89288ef/5DEE4274/t51.2885-19/s150x150/45800263_292367228060639_7930850900988395520_n.jpg?_nc_ht=scontent-cdg2-1.cdninstagram.com',
          'username': 'messhland'},
 'user_id': 9486442541}
```

**Comment by ping** [comment]
This library does not manipulate the api response. What you see is what has been sent by the server.
