### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by remi2j** [ping/instagram_private_api#192]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [ x Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Instagram can change its API and privacy policy at any moment, creating breaking changes for this project. This repo needs to be actively maintained to be reliable for production use. Is this the case ?

I'm asking because:
* There has been no commits in 6 months
* The owner hasn't replied to an issue in months
* There are 19 open PRs.

Thanks

**Comment by ping** [comment]
This is a hobbyist project at best, and is not meant for any "production" use whatsoever.

**Comment by ghost** [comment]
Unfortunately the project seems abandoned, Instagram has changed a lot so this project is really outdated. I don't know if this project has an active and updated fork but there is another API which is really complete and up-to-date, the difference is that it's not python but JS. https://github.com/dilame/instagram-private-api
