### ISSUE TITLE
I need app's api to accept the  pending follow  Request

### ISSUE THREAD

**Issue by Jagansivam28** [ping/instagram_private_api#196]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the lastest version v1.6.0
- [ ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe your Feature Request:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

**Comment by ping** [comment]
Great. Submit a PR.

**Comment by VityaSchel** [comment]
> Great. Submit a PR.

![image](https://user-images.githubusercontent.com/59040542/190866039-4d8caf6b-5866-43d4-b03e-467a81c96239.png)

skunk
