### ISSUE TITLE
There is no media_likers-next_max_id !

### ISSUE THREAD

**Issue by ismcagilci** [ping/instagram_private_api#199]
Hello i am Ismail ,

I want to get users from medias who likes but when i try to get data from api.media_likers i , i cant see next_max_id . In this situation there are 2 options for this issue : Instagram doesnt give this value or this api doesnt have media_likers next_max_id but it seems api problem because other api has next_max_id for media_likers .

Can you help me?

**Comment by amirpdlll** [comment]
Hello , I have the same problem ! how can I make pagination for likers of a media ? 
Besides in this function 
`api.media_likers(media_id='***',count=20)	`
count doesn't work and also I set count 20 it returns 999 likers usernames ! 
what is wrong ? and how can I use this function
thanks
