### ISSUE TITLE
Pickle data was truncated, then trying to load cookies to main Client class

### ISSUE THREAD

**Issue by ovvesomeguy** [ping/instagram_private_api#202]
I have a file with cookies with name "file.session"
How i`m getting string from them:

```python
def get_cookies_from_file():
    with open('file.session' , 'rb') as file:
        cook = file.read()
    cook = cook.get_dict()
    found = ['%s=%s' % (name, value) for (name, value) in cook.items()]
    string = ';'.join(found)
```
This function return string like:
```bash
csrftoken=abcd;ds_user_id=abcd;
```
After that i`m trying to load this string to Client:

```python
client = Client('username' , 'password' , cookie=string)
```
And getting this error:

```bash
    cookie_jar = ClientCookieJar(cookie_string=cookie_string)
  File "/home/hasan/.local/lib/python3.6/site-packages/instagram_private_api/http.py", line 19, in __init__
    self._cookies = compat_pickle.loads(cookie_string.encode('utf-8'))
_pickle.UnpicklingError: pickle data was truncated
```

 I`m tried to change ClientCookieJar, but nothing works. After that i'm tried to change the string type to:
```bash
csrftoken=abcd&ds_user_id=abcd
```
But it not helps. I don't know why pickle truncate the string. Maybe the string must be not 'string' type, maybe it must be pickle object?
 
Client that i`m using
- [x] app
- [ ] web

Client version
- [x] 1.6.0.0

Python version
- [x] Python 3.6.8

**Comment by ping** [comment]
The cookie_string must be from an existing``ClientCookieJar.dump()``, not an arbitrary string format.
