### ISSUE TITLE
I want to create an app that logs in with Instagram, can I use this after the user is authenticated?

### ISSUE THREAD

**Issue by samirchahine** [ping/instagram_private_api#205]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

After the user authenticates with my application, I will receive a token.

Am I able to use that token to then login with this API so I can use it's functionality, if not is there a way for the user to login with their instagram credentials (without plaintext) so they can cache their settings like the `savesettings.py` example?

Thank you! 😊

**Comment by samirchahine** [comment]
Hi @ping ! 

After request the `access_token` from the Instagram Platform API I realised it gives close to nothing and it will be deprecated anyway early 2020. Is there a way I can utilise this library in an application so users can see they're own data etc. ?

**Comment by samirchahine** [comment]
Any update on this @ping  ?

**Comment by ping** [comment]
This library uses the _private API_ as evident by its name. It doesn't work in any way with the official API.
