### ISSUE TITLE
Paginate through stories feed

### ISSUE THREAD

**Issue by romshiri** [ping/instagram_private_api#207]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

---

Paste the output of ``python -V`` here: Python 2.7.10

I'm trying to paginate through stories feed of a specific hashtag but I'm not sure how to achieve that. The total result is 20 items and I don't see any 'next_max_int" API for getting the next page. Any idea how to do that? Perhaps a different API could be the answer.

**Update:** 
I've tried the app API that does have pagination mechanism using 'next_max_int' but the results are the same.

**Update 2:**
Tried to replicate the way the app/web works - stories that have been seen are no longer fetched.
Still not working.

```python
status = api.media_seen(items) # status OK -> story is still fetched next time.
```

Thanks.

Web API Code:

```python
authed_web_api = MyClient(auto_patch=True, authenticate=True, username='XXXX', password='XXXX')

result = authed_web_api.tag_story_feed(hashtag)
result2 = authed_web_api.tag_story_feed(hashtag)

items1 = result["data"]["reels_media"][0]["items"]
items2 = result2["data"]["reels_media"][0]["items"] # same data
```

App API Code:

```python
api = Client(user_name, password)
result = api.feed_tag(hashtag, api.generate_uuid())
football_stories = result["story"]["items"]
next_max_id = result.get('next_max_id')

items = []
result = api.feed_tag(hashtag, api.generate_uuid())
items.extend(result["story"]["items"])
next_max_id = result.get('next_max_id')

while next_max_id:
    result = api.feed_tag(hashtag, api.generate_uuid(), max_id=next_max_id)
    items.extend(result["story"]["items"])
    if len(items) >= 100:       
        break
    next_max_id = result.get('next_max_id')


for story in items: 
    print(story["pk"]) # PK IDs repeat themselves 
```

**Comment by ping** [comment]
Please check the pagination example carefully. The rank_token has to be retained and not re-generated with every call.
