### ISSUE TITLE
Is there any way to make the tag a variable when using tag_feed?

### ISSUE THREAD

**Issue by Radiocalypse** [ping/instagram_private_api#209]
---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Right now, if you search a tag on Instagram, posts will be pulled that are relative to that tag, but there will be posts from 2 hours ago, 4 hours, 12 hours, etc. I want to write a script that will only pull posts that were made within the last hour, and I have to make the tag a variable. Is there any way to do this?

---

### Paste the output of ``python -V`` here:

Python 3.7.3
```

**Comment by ping** [comment]
Your question is more suited for stackoverflow.
