### ISSUE TITLE
ClientError checkpoint_challenge_required

### ISSUE THREAD

**Issue by gregkr** [ping/instagram_private_api#210]
-----
### Before submitting an issue, make sure you have:
- [+] Updated to the lastest version v1.6.0
- [+] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [+] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [+] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [+] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

I usually use user data stored in a file. Today I decided to update this file. And got an error ( see bolow). 
---

Paste the output of ``python -V`` here:  Python 2.7.16 

Error/Debug Log:

```
ClientError checkpoint_challenge_required (Code: 400, Response: {"status": "fail", "message": "challenge_required", "error_type": "checkpoint_challenge_required", "challenge": {"api_path": "/challenge/8166970138/kX2s7GUDNY/", "native_flow": true, "url": "https://i.instagram.com/challenge/8166970138/kX2s7GUDNY/", "lock": true, "logout": false, "hide_webview_header": true}})
```

What I should do?

**Comment by kostyakoz** [comment]
Got same problem few days ago.

`ClientError checkpoint_challenge_required (Code: 400, Response: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/18077214266/uoks7HgTin/", "api_path": "/challenge/18077214266/uoks7HgTin/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"})`

**Comment by ping** [comment]
https://instagram-private-api.readthedocs.io/en/latest/faq.html#what-does-checkpoint-challenge-required-challenge-required-mean
