### ISSUE TITLE
[QUESTION] X-IG-Capabilities header

### ISSUE THREAD

**Issue by disco-mayhem** [ping/instagram_private_api#214]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:
Hello.
Are there any changes to X-IG-Capabilities header since https://github.com/ping/instagram_private_api/commit/8eb3d726360cce264a586a0a68bc778882f41c81 commit?

Decoding current constant using old method returns negative number, I'm not sure if this is correct.
Where did the previous "seed" numbers come from (244445, 131316445, etc)? There is no such APK versions.

Guys from Instabot just took the current version number (https://github.com/instagrambot/instabot/commit/4ff32f942dc6e574bfe44c0a70c394c2b82d3596) and I want to know they are doing right.

Thank you!

**Comment by ping** [comment]
> Issues about reverse engineering is out of scope and will be closed without response.
