### ISSUE TITLE
User_agent support for iOS

### ISSUE THREAD

**Issue by coisan** [ping/instagram_private_api#216]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Feature Request:

Currently there is support only for user_agent in Android template, iOS is not accepted. Now this is especially useful, since using a new different user agent (ideally same device as the actual smartphone used) prevents the latest often soft bans.

Default one from API
`Instagram 76.0.0.15.395 Android (24/7.0; 640dpi; 1440x2560; samsung; SM-G930F; herolte; samsungexynos8890; en_US; 138226743)`

One from an iPhone XS
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/78.0.3904.84 Mobile/15E148 Safari/604.1`

More examples [over here](https://user-agents.net/applications/instagram-app).

**Comment by Asteur** [comment]
You need to jailbreak your iPhone to get the right parameters...

**Comment by Asteur** [comment]
Check https://github.com/ping/instagram_private_api/blob/master/instagram_private_api/constants.py

**Comment by coisan** [comment]
@Asteur Thank you for the suggestion, but I already had a look over the constants definition and it is not quite up to date. I had in mind to use an iOS user_agent to mimic the one used by my phone, on which I can do actions without block. With the default Android user_agent implemented in this API I get block after 10 actions...

**Comment by ping** [comment]
This library emulates an Android device. There is no intention to support the iOS equivalent.
