### ISSUE TITLE
Archive/unarchive media isn't working

### ISSUE THREAD

**Issue by sudoguy** [ping/instagram_private_api#22]
### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Python 2.7.12

Code:

```python
from instagram_private_api import Client, ClientCompatPatch

user_name = 'username'
password = 'password'

api = Client(user_name, password)
results = api.username_feed(user_name)
items = results.get('items', [])
for item in items:
    ClientCompatPatch.media(item)
    api.media_only_me(item['pk'], item['media_type'])
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "/home/user/github/instagram_private_api/examples/archive.py", line 13, in <module>
    api.media_only_me(item['pk'], item['media_type'])
  File "/home/user/github/instagram_private_api/instagram_private_api/endpoints/media.py", line 506, in media_only_me
    res = self._call_api(endpoint, params=params, query={'media_type': media_type})
  File "/home/user/github/instagram_private_api/instagram_private_api/client.py", line 484, in _call_api
    raise ClientError(error_msg, e.code, error_response)
instagram_private_api.errors.ClientError: Bad Request: invalid parameters
```

---

### Describe your issue

Archive/unarchive media isn't working. Error message: 'Bad Request: invalid parameters'. It looks like the api has changed.

**Comment by ping** [comment]
You should be using ``item['id']``, not ``item['pk']``.

**Comment by sudoguy** [comment]
@ping Thanks! It works!
