### ISSUE TITLE
Example for posting an album

### ISSUE THREAD

**Issue by SaliZumberi** [ping/instagram_private_api#220]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the lastest version v1.6.0
- [ ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x ] app (``instagram_private_api/``)
- [x ] web (``instagram_web_api/``)

---

### Describe your Question/
Can someone show me how I can post an album? Is there an example? Would be very happy if someone could help me out

Best
sali

**Comment by ping** [comment]
Please review the documentation before submitting an issue.

> Before submitting an issue, make sure you have:

> [ ] Updated to the lastest version v1.6.0
> [ ] Read the README and docs
> [ ] Searched the bugtracker for similar issues including closed ones
> [ ] Reviewed the sample code in tests and examples
