### ISSUE TITLE
"reels_tray" endpoint no longer returning replays of archived live broadcasts

### ISSUE THREAD

**Issue by callten** [ping/instagram_private_api#23]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [X] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [X] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

web_api = Client()
user_feed_info = web_api.user_feed('1234567890', count=10)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below
GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofDBlVEA37II3LI7YdHeiMrd9ylj; mid=WFI52QABAAGrbKL-OZ4DtgLd9QIf
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```http
# Please provide your capture below
HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 15 Dec 2016 08:50:19 GMT
Content-Type: application/json
Set-Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; expires=Thu, 14-Dec-2017 08:50:19 GMT; Max-Age=31449600; Path=/; secure
Connection: keep-alive
Content-Length: 16

{"status": "ok"}
```
---

### Describe your issue

I didn't want to call it a bug (because I'm sure there's nothing wrong with your excellent project) but it seems as if they've changed the way this endpoint works. I can see archived live broadcasts on the app on my phone and a couple of days ago there was a ['post_live'] key in the json returned by the above api call (if there were in fact archived live broadcasts in the tray) but now that key never seems to exist. An api call to user_story_feed with their uid also fails to return "post live" broadcasts, despite them showing up in the app on my phone...

**Comment by ping** [comment]
Testing this is a pain because of the difficulty in finding accounts with replays, but both endpoints are still working as far as I can tell. I just checked with an account that currently has a replay.

Provide a full debug log for ``user_story_feed `` with a user account that has a replay available at least for the next 12 hours. Also a debug print of the user agent:

```python
api = Client('username', 'password')
print(api.user_agent)
```

**Comment by callten** [comment]
You're not kidding about it being hard to find accounts with replays! It doesn't help that they seem to randomly decide whether or not to show the "top live" tray item on the search page. Anyway, the one that I noticed the problem with is no longer available, I've just searched for a good while and found user 297330467, results of user_story_feed are as follows:

`{"broadcast": null, "reel": {"id": 297330467, "expiring_at": 1500077092, "prefetch_count": 0, "latest_reel_media": 1499990692, "seen": 0.0, "can_reply": true, "items": [{"story_polls": [], "has_more_comments": false, "photo_of_you": false, "caption_position": 0.0, "has_audio": true, "video_duration": 15, "story_hashtags": [], "client_cache_key": "MTU1ODE2MDg0MDA0MTMyMTY3OQ==.2", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "has_liked": false, "like_count": 0, "preview_comments": [], "device_timestamp": 1499966807, "story_locations": [], "likers": [], "filter_type": 0, "pk": 1558160840041321679, "video_versions": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/17095007_1816007688715027_2336776712299216896_n.mp4", "type": 101, "height": 1136, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/15974360_1867198066933254_8423370039364681728_n.mp4", "type": 103, "height": 852, "width": 480}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/15974360_1867198066933254_8423370039364681728_n.mp4", "type": 102, "height": 852, "width": 480}], "expiring_at": 1500053207, "image_versions2": {"candidates": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p640x640/17096527_339739473125810_3224363018624172032_n.jpg?ig_cache_key=MTU1ODE2MDg0MDA0MTMyMTY3OQ%3D%3D.2", "height": 1136, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p240x240/17096527_339739473125810_3224363018624172032_n.jpg?ig_cache_key=MTU1ODE2MDg0MDA0MTMyMTY3OQ%3D%3D.2", "height": 426, "width": 240}]}, "comment_count": 0, "id": "1558160840041321679_297330467", "media_type": 2, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZjE4YWQ5ZTg2NzQ1NDM1NGJiMDBhNTE2NDkxMTQ3NjIxNTU4MTYwODQwMDQxMzIxNjc5Iiwic2VydmVyX3Rva2VuIjoiMTUwMDAyOTIxMDAyOXwxNTU4MTYwODQwMDQxMzIxNjc5fDE3MTQ2MDAyMDJ8MTFjMDJjNGI4NWJmNDU0ZGZmODI4NmM0NjU0OWJmZTc2OWFhMThkZDBmODhhMGRjYjZhM2RkYTI3MzY5ZDFiMyJ9LCJzaWduYXR1cmUiOiIifQ==", "comment_threading_enabled": false, "can_viewer_save": true, "comment_likes_enabled": false, "max_num_visible_preview_comments": 4, "taken_at": 1499966807, "reel_mentions": [{"is_pinned": 0, "user": {"full_name": "Shaheem Royal \ud83d\udc51", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/18950243_1961864497435586_1551908092206120960_a.jpg", "is_private": false, "profile_pic_id": "1531833585496220421_5564616408", "is_verified": false, "username": "shopshaheemroyal", "pk": 5564616408}, "width": 0.5019012550497428, "height": 0.03597751175300561, "x": 0.5550770855347423, "rotation": 0.0, "y": 0.5828378754963144}], "is_reel_media": true, "caption": {"did_report_as_spam": false, "type": 1, "created_at_utc": 1499967276, "user_id": 297330467, "status": "Active", "text": "Follow my big brother new brand \n@shopshaheemroyal", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "media_id": 1558160840041321679, "content_type": "comment", "bit_flags": 0, "created_at": 1499967276, "pk": 17876593906114813}, "code": "BWfswdNllTP", "original_height": 1279, "original_width": 720, "caption_is_edited": false}, {"story_polls": [], "has_more_comments": false, "photo_of_you": false, "caption_position": 0.0, "has_audio": true, "video_duration": 15.111678, "story_hashtags": [], "client_cache_key": "MTU1ODIxOTI5ODcyMzg0NDU3OA==.2", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "has_liked": false, "like_count": 0, "preview_comments": [], "device_timestamp": 1499973739, "story_locations": [], "likers": [], "filter_type": 0, "pk": 1558219298723844578, "video_versions": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/18420543_570021123168375_7547028962443001856_n.mp4", "type": 101, "height": 1137, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/19572178_123174588294423_905742116632657920_n.mp4", "type": 103, "height": 853, "width": 480}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/19572178_123174588294423_905742116632657920_n.mp4", "type": 102, "height": 853, "width": 480}], "expiring_at": 1500060138, "image_versions2": {"candidates": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p640x640/13195626_316950568716253_1901182121276342272_n.jpg?ig_cache_key=MTU1ODIxOTI5ODcyMzg0NDU3OA%3D%3D.2", "height": 1137, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p240x240/13195626_316950568716253_1901182121276342272_n.jpg?ig_cache_key=MTU1ODIxOTI5ODcyMzg0NDU3OA%3D%3D.2", "height": 426, "width": 240}]}, "comment_count": 0, "id": "1558219298723844578_297330467", "media_type": 2, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZjE4YWQ5ZTg2NzQ1NDM1NGJiMDBhNTE2NDkxMTQ3NjIxNTU4MjE5Mjk4NzIzODQ0NTc4Iiwic2VydmVyX3Rva2VuIjoiMTUwMDAyOTIxMDAyOXwxNTU4MjE5Mjk4NzIzODQ0NTc4fDE3MTQ2MDAyMDJ8Y2NjMDEyNDY5ZDc5ZjdhMDM2OWYyNmE0YWQzYWQwN2IyMzkxN2ZmMTZhZjJiYWIzYjQ1MDQ3MjE2OGFjM2U0ZCJ9LCJzaWduYXR1cmUiOiIifQ==", "comment_threading_enabled": false, "can_viewer_save": true, "comment_likes_enabled": false, "max_num_visible_preview_comments": 4, "taken_at": 1499973738, "reel_mentions": [], "is_reel_media": true, "caption": {"did_report_as_spam": false, "type": 1, "created_at_utc": 1499974244, "user_id": 297330467, "status": "Active", "text": "\ud83d\udd25 \"Kida who you get your dancing from\" \ud83e\udd26\ud83c\udffe\u200d\u2642\ufe0f", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "media_id": 1558219298723844578, "content_type": "comment", "bit_flags": 0, "created_at": 1499974244, "pk": 17876984671096097}, "code": "BWf6DJGl9Hi", "original_height": 1280, "original_width": 720, "caption_is_edited": false}, {"story_polls": [], "has_more_comments": false, "photo_of_you": false, "caption_position": 0.0, "has_audio": true, "video_duration": 15.078345, "story_hashtags": [], "client_cache_key": "MTU1ODM1Njc0ODEwNDMyNjM1OA==.2", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "has_liked": false, "like_count": 0, "preview_comments": [], "device_timestamp": 1499990142, "story_locations": [], "likers": [], "filter_type": 0, "pk": 1558356748104326358, "video_versions": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/14329497_784474925063723_2912179858970771456_n.mp4", "type": 101, "height": 1137, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/16469805_1423163454471982_7431798838182019072_n.mp4", "type": 103, "height": 853, "width": 480}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/16469805_1423163454471982_7431798838182019072_n.mp4", "type": 102, "height": 853, "width": 480}], "expiring_at": 1500076542, "image_versions2": {"candidates": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p640x640/15973990_246632472494068_4207311656348286976_n.jpg?ig_cache_key=MTU1ODM1Njc0ODEwNDMyNjM1OA%3D%3D.2", "height": 1137, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p240x240/15973990_246632472494068_4207311656348286976_n.jpg?ig_cache_key=MTU1ODM1Njc0ODEwNDMyNjM1OA%3D%3D.2", "height": 426, "width": 240}]}, "comment_count": 0, "id": "1558356748104326358_297330467", "media_type": 2, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZjE4YWQ5ZTg2NzQ1NDM1NGJiMDBhNTE2NDkxMTQ3NjIxNTU4MzU2NzQ4MTA0MzI2MzU4Iiwic2VydmVyX3Rva2VuIjoiMTUwMDAyOTIxMDAyOHwxNTU4MzU2NzQ4MTA0MzI2MzU4fDE3MTQ2MDAyMDJ8YzMyNTY5N2UyYmY3NjUxYmFjZmFkZGIyYWZjYTZmZTEzMjJiMzY3YjI1YWI1ZWFkNDIxODI2OGM1ZTI2MDhlYiJ9LCJzaWduYXR1cmUiOiIifQ==", "comment_threading_enabled": false, "can_viewer_save": true, "comment_likes_enabled": false, "max_num_visible_preview_comments": 4, "taken_at": 1499990142, "reel_mentions": [{"is_pinned": 0, "user": {"full_name": "Randy Hill", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/12568262_975638795815752_1697691639_a.jpg", "is_private": false, "is_verified": false, "username": "rancutyou", "pk": 1800772040}, "width": 0.482734375, "height": 0.06011525487256372, "x": 0.35009765625, "rotation": 0.0, "y": 0.5724114505247376}], "is_reel_media": true, "caption": {"did_report_as_spam": false, "type": 1, "created_at_utc": 1499990633, "user_id": 297330467, "status": "Active", "text": "@rancutyou with the clippers\u26a1\ufe0f\ud83d\udca6\ud83c\udfc6\ud83d\udc88", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "media_id": 1558356748104326358, "content_type": "comment", "bit_flags": 0, "created_at": 1499990633, "pk": 17875425664121834}, "code": "BWgZTS0F1zW", "original_height": 1280, "original_width": 720, "caption_is_edited": false}, {"story_polls": [], "has_more_comments": false, "photo_of_you": false, "caption_position": 0.0, "has_audio": true, "video_duration": 15.088345, "story_hashtags": [], "client_cache_key": "MTU1ODM1NzcyOTc0NzQyOTA5NQ==.2", "user": {"is_unpublished": false, "full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_favorite": false, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "is_verified": true, "has_anonymous_profile_picture": false, "username": "kidathegreat", "pk": 297330467}, "has_liked": false, "like_count": 0, "preview_comments": [], "device_timestamp": 1499990692, "story_locations": [], "likers": [], "filter_type": 0, "pk": 1558357729747429095, "video_versions": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/13706705_1895308690723455_6776223405306806272_n.mp4", "type": 101, "height": 1137, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/15973957_1903802456543744_1620745951125700608_n.mp4", "type": 103, "height": 853, "width": 480}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t50.9793-16/15973957_1903802456543744_1620745951125700608_n.mp4", "type": 102, "height": 853, "width": 480}], "expiring_at": 1500077092, "image_versions2": {"candidates": [{"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p640x640/14704550_270887020058363_6450299816344813568_n.jpg?ig_cache_key=MTU1ODM1NzcyOTc0NzQyOTA5NQ%3D%3D.2", "height": 1137, "width": 640}, {"url": "https://scontent-cdg2-1.cdninstagram.com/t51.9792-15/e15/p240x240/14704550_270887020058363_6450299816344813568_n.jpg?ig_cache_key=MTU1ODM1NzcyOTc0NzQyOTA5NQ%3D%3D.2", "height": 426, "width": 240}]}, "comment_count": 0, "id": "1558357729747429095_297330467", "media_type": 2, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZjE4YWQ5ZTg2NzQ1NDM1NGJiMDBhNTE2NDkxMTQ3NjIxNTU4MzU3NzI5NzQ3NDI5MDk1Iiwic2VydmVyX3Rva2VuIjoiMTUwMDAyOTIxMDAyOHwxNTU4MzU3NzI5NzQ3NDI5MDk1fDE3MTQ2MDAyMDJ8NjdkMDNhNzU2ZmEzYzRiMWY2ZjU1YTg5ZDdkZWY2ZTBiYjJlOTcwNzYyYjg0NTk5YWYzMGNhM2M5MTUyMmM0NSJ9LCJzaWduYXR1cmUiOiIifQ==", "comment_threading_enabled": false, "can_viewer_save": true, "comment_likes_enabled": false, "max_num_visible_preview_comments": 4, "taken_at": 1499990692, "reel_mentions": [], "is_reel_media": true, "caption": null, "code": "BWgZhlClGbn", "original_height": 1280, "original_width": 720, "caption_is_edited": false}], "user": {"full_name": "KidaTheGreat\u2122\ud83d\udd7a\ud83c\udffe", "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/14272036_187435451679908_1533631605_a.jpg", "is_verified": true, "is_private": false, "profile_pic_id": "1339535820092269890_297330467", "friendship_status": {"is_bestie": false, "blocking": false, "followed_by": false, "is_private": false, "following": true, "incoming_request": false, "outgoing_request": false}, "username": "kidathegreat", "pk": 297330467}}, "status": "ok"}`

Results of user_agent:
`Instagram 10.23.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G930F; herolte; samsungexynos8890; en_US)`

**Comment by ping** [comment]
You're either not using the latest version of the lib or you're overriding the default user agent with your saved settings.

If you're already using the latest release, you should either 1) remove the following from  your saved settings:
- 'signature_key'
- 'key_version'
- 'ig_capabilities'
- 'app_version'
- 'android_release'
- 'android_version'
- 'phone_manufacturer'
- 'phone_device'
- 'phone_model'
- 'phone_dpi'
- 'phone_resolution'
- 'phone_chipset'

or 2) just purge your old saved settings and login afresh.

**Comment by callten** [comment]
Ahhh yes that's right. I was using a tool which used your libraries and it was only using 1.3.3. I've updated the libs it uses to 1.3.5 and it's working now, thank you. It remains to be seen whether the other tool works with 1.3.5 but I don't see why it shouldn't...
