### ISSUE TITLE
Cant get next page of search query

### ISSUE THREAD

**Issue by qwertyNodes** [ping/instagram_private_api#235]
Hi, im trying to get users who posted with some hashtag, so I'm using top search query using this method:
`results = api.top_search('fitness')`
but in results im getting just 25 users. How i can get the next page of users from the search query.

**Comment by wlerin** [comment]
Short answer: you can't.

It requires pagination, probably using the rank_token method, but top_search doesn't allow you to specify a rank_token, nor does it return the one for the next set of results.
