### ISSUE TITLE
APP API: likes are not deployed

### ISSUE THREAD

**Issue by michaelgreyskull** [ping/instagram_private_api#236]
Hi,

it's great to see an automation library for social media! However I experience a strange behaviour:
After liking a post using the APP api, I checked if the media is really liked and this seems to be not the case.
Please see this minimal example code:

```
likedstatus = api.post_like(mediaid, module_name='feed_timeline')['status']
print("Liked media {} - status: {}".format(mediaid,likedstatus))

likerslist = []
for item in api.media_likers(mediaid)["users"]:
	likerslist.append(item["username"])
if args.username not in likerslist:
	print("media liked but user not in likers list")
```

The first part "likes" a post with a media_id I obtained earlier. Status says "ok". But when I check if the current user is in the list of users who liked this media, it is not. Thus the last print is shown on screen and if I double check via browser/mobile, the corresponding media post ist not liked.

Am I using the `post_like` method in a wrong way?

Thanks for reading! Any hint is appreciated!

**Comment by michaelgreyskull** [comment]
Excuse me, why got this issue closed without a comment?

**Comment by ghost** [comment]
Maybe for the no template.I suggest you to use the [NodeJS api](https://github.com/dilame/instagram-private-api), it works better. This one gives me many headaches, and it's outdated.
