### ISSUE TITLE
[question]Is it safe to use upload.py ?

### ISSUE THREAD

**Issue by ishandutta2007** [ping/instagram_private_api#237]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Feature Request:

The reason I am skeptic is instagram no longer relies on IP much but more on uniqueness of the mobile attributes(aka device fingerprints) to detect spam. This API doesn't spoof device attributes, so if anyone who is using this API to post for 100+ accounts can comment?

**Comment by ishandutta2007** [comment]
Hello ???

**Comment by ishandutta2007** [comment]
@ping if you haven't experienced  keep it open, someone in community might have. Let them share their experience.

**Comment by ishandutta2007** [comment]
@bolds07 great question https://github.com/ping/instagram_private_api/issues/239.
Unless you are able to spoof all the device fingerprints, private API is of no use in todays world.
I don't understand why the repo owner blindly closes all the issues even without triaging them

**Comment by dvingerh** [comment]
Because you dont use the template and guidelines set by the repo owner

**Comment by ishandutta2007** [comment]
@notcammy not everything can be put into templates, this is more of a discussion than bug report, stackoverflow doesn't have templates. Had the repo owner been answering/discussing about it on stackoverflow(or any other forum of his choice) we would have happily moved there .

**Comment by ishandutta2007** [comment]
@notcammy this https://github.com/ping/instagram_private_api/issues/239 very much has been written in template. and if thats a concern here you go updated this issue too.

**Comment by dvingerh** [comment]
> - Issues about reverse engineering is out of scope and will be closed without response.

**Comment by ishandutta2007** [comment]
@notcammy which part of my question asks for reverse engineering ?

**Comment by dvingerh** [comment]
Not your question, #239's
Your issue was missing the template that is why it was closed

**Comment by ishandutta2007** [comment]
@notcammy I don't even have a deep enough understanding of this codebase yet to suggest reverse engineering, I had just creating a thread to know people's experience with this code, how many people got their account flagged/deactivated for using this on multiple accounts. if @ping doesn't have any experience he/she may not comment, let others who have do.

**Comment by ishandutta2007** [comment]
@notcammy @ping should I recreate the issue or wait more for it to be reopened?

**Comment by ghost** [comment]
I stopped using this library, it has many issues, they are closed and it's outdated. I use node JS library, it's better imo https://github.com/dilame/instagram-private-api.

**Comment by helpsocialbotspy** [comment]
@ghost Can you show one of your instagram profile account which you have botted. Generally a  botted instagram account looses engagement.
