### ISSUE TITLE
Will this API work after 31 Mrach 2020

### ISSUE THREAD

**Issue by Suleman-Elahi** [ping/instagram_private_api#241]
### Describe your Question/Issue:

Facebook is shutting the legacy API platform, so my question is that, will this private API still work?

![image](https://user-images.githubusercontent.com/24384996/75427716-03e70300-596d-11ea-97fa-f940d3257096.png)

**Comment by dvingerh** [comment]
Things should stay working as far as I'm aware.
See  https://github.com/ping/instagram_private_api/issues/52 and https://github.com/ping/instagram_private_api/issues/65

**Comment by wlerin** [comment]
This doesn't use the public API, so it won't be affected by that directly. However, it's possible they may change the backend at the same time (or any other time, without warning).
