### ISSUE TITLE
How to get the contents of an highlight tray

### ISSUE THREAD

**Issue by rcpinheiro** [ping/instagram_private_api#249]
Hi!

 I successfully got the highlights tray from a certain user:
```
feed = ig_client.highlights_user_feed(user_id)
```
 It returns all the trays information, including the ID (something like: "highlight:17860034797000000")

 The problem is that I couldn't find in the docs how to fetch the contents of a certain tray, at least in the Private API (in the Web API there's a highlight_reel_media() function to do just that.
 Will I have to use the Web API to do this or is there a way to do it with the Private API?
 Thanks in advance!

**Comment by autoiue** [comment]
You can use the `reels_media` endpoint passing a list of highlight IDs(like `"highlight:17860034797000000"` and user IDs (it can be mixed).

**Comment by rcpinheiro** [comment]
Thanks @procsynth , it works. That info should be in the docs, imho.
