### ISSUE TITLE
Media_count always 0 in tag_info

### ISSUE THREAD

**Issue by suffrage** [ping/instagram_private_api#25]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.5
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 2.7.10

Code:

```python
api.tag_search("instaday")

...

{
      "media_count": 12442501, 
      "name": "instaday", 
      "id": 17843910382056994
}, 

...

api.tag_info(17843910382056994)

...

{
    "profile": null, 
    "status": "ok", 
    "media_count": 0
}
```

Error/Debug Log:

```python
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http

```

Response:

```http

```
---

### Describe your issue

When call tag_info media_count always 0

**Comment by ping** [comment]
You should be using the actual tag 'instaday', not the ID. Please properly review the sample code in ``tests/`` in the future.

**Comment by suffrage** [comment]
This is not obvious from the documentation

`tag_search(text, **kwargs)`

`tag_info(tag)`

**Comment by ping** [comment]
In the issue template, you have checked
``[x] Reviewed the sample code in tests and examples``

[tests/private/tags.py](https://github.com/ping/instagram_private_api/blob/master/tests/private/tags.py#L25)
```python
    def test_tag_info(self):
        results = self.api.tag_info('catsofinstagram')
        self.assertEqual(results.get('status'), 'ok')
        self.assertGreater(results.get('media_count'), 0, 'No media_count returned.')
```

If the documentation is deficient, PRs are always welcomed to improve them.
