### ISSUE TITLE
How do I get my max_id for api.user_feed?

### ISSUE THREAD

**Issue by y3** [ping/instagram_private_api#253]
I am using the app api and trying to get someone's feed but it only gets 12 posts, and I don't understand how to get the max_id. Can anyone explain?

**Comment by olliechick** [comment]
`feed = api.user_feed(user_id)` will return the posts in `feed['posts']`, which are where you're getting the latest 12 posts. `feed['next_max_id']` will give you the max_id which you then pass in as `feed = api.user_feed(user_id, max_id=max_id)`.

Here's an example code block to get all the posts from a given user with id `user_id`:
```
more_available_key = 'more_available'
next_max_id_key = 'next_max_id'
items_key = 'items'

feed = api.user_feed(user_id)
posts = feed[items_key]

while feed[more_available_key]:
    print(f"Getting more posts ({len(posts)} so far)...")
    max_id = feed[next_max_id_key]
    feed = api.user_feed(user_id, max_id=max_id)
    posts.extend(feed[items_key])
```
