### ISSUE TITLE
How to avoid losing connections

### ISSUE THREAD

**Issue by comtong** [ping/instagram_private_api#26]
This project is really great, It's absolutely omnipotent.
But I still have some obstacles.
when I use it,It happens all the time
1. urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>
2. ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
then, how to avoid it

**Comment by ping** [comment]
@comtong

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
