### ISSUE TITLE
checkpoint_challenge

### ISSUE THREAD

**Issue by Hantoo** [ping/instagram_private_api#263]
Even after logging onto instagram web, clicking "this was me" and then trying to re-log in. 
Every time I get a checkpoint_challenge_required.

Any advice how to fix this?

**Comment by redpwilliams** [comment]
I also faced this issue. The first time, it was solved by responding to the email and confirming it was me, I think Instagram would have thought that it came from somebody else. But the next time I encountered the same issue. I couldn't even log in to my account (via the app).

**Comment by phlaskoo** [comment]
> Even after logging onto instagram web, clicking "this was me" and then trying to re-log in.
> Every time I get a checkpoint_challenge_required.
> 
> Any advice how to fix this?

hi, i had the same problem ... log in to instagram with your browser then go setting/log in activities and confirm all your log in 
then it's ok 
it worked for me...hope to be useful foryou

**Comment by peylight** [comment]
@phlaskoo
i try to confirm it but not working for me!
Maybe we need to change instagram signed key?

**Comment by bamtan** [comment]
You could try the referenced fork in this comment regarding a way to solve the checkpoint_challenge https://github.com/dvingerh/PyInstaLive/issues/57#issuecomment-611120095

**Comment by ghost** [comment]
It's probably not correctly implemented because in the NodeJS library it works fine https://github.com/dilame/instagram-private-api
