### ISSUE TITLE
media_info2(short_code) endpoint has been limited by instagram

### ISSUE THREAD

**Issue by zahra-ash0uri** [ping/instagram_private_api#266]
Since 19 May 2020, the endpoint to get information of posts (without authentication) has been banned by instagram. I noticed this issue while using web client without authentication. Actually, the error is:
```
Expecting value: line 1 column 1 (char 0)
```
Do you have any solution to get rid of it?

**Comment by zahra-ash0uri** [comment]
> Since 19 May 2020, the endpoint to get information of posts (without authentication) has been banned by instagram. I noticed this issue while using web client without authentication. Actually, the error is:
> 
> ```
> Expecting value: line 1 column 1 (char 0)
> ```
> 
> Do you have any solution to get rid of it?

The endpoint url has been changed, and with some little changes in response data. You should edit instagram_web_api/client.py in method media_info2 as below.
```python
   def media_info2(self, short_code):
        """
        Alternative method to get media info. This method works for carousel media.

        :param short_code: A media's shortcode
        :param kwargs:
        :return:
        """
        headers = {
            'User-Agent': self.user_agent,
            'Accept': '*/*',
            'Accept-Language': 'en-US',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'close',
            'Referer': 'https://www.instagram.com',
            'x-requested-with': 'XMLHttpRequest',
        }
        # info = self._make_request(
        #     'https://www.instagram.com/p/{0!s}/'.format(short_code),
        #     query={'__a': '1', '__b': '1'},
        #     headers=headers)
        endpoint = "https://www.instagram.com/graphql/query/?query_hash=8c1ccd0d1cab582bafc9df9f5983e80d&variables=%7B%22shortcode%22%3A%22{short_code}%22%2C%22child_comment_count%22%3A3%2C%22fetch_comment_count%22%3A40%2C%22parent_comment_count%22%3A24%2C%22has_threaded_comments%22%3Atrue%7D".format(short_code=short_code)
        info = self._make_request(url=endpoint, headers=headers)
        media = info.get('data', {}).get('shortcode_media', {})
        # media = info.get('graphql', {}).get('shortcode_media', {})
        if self.auto_patch:
            media = ClientCompatPatch.media(media, drop_incompat_keys=self.drop_incompat_keys)
        return media
```

**Comment by mswdevsla** [comment]
@zahra-ash0uri Thank you.  
Your answer was very helpful. And I have a question.
I could have used query_hash to get all the images. but I wonder if this query_hash alone can continue to work.

is there no limit to query_hash?
For example, can import all Instagram images with only a certain query_hash, or is there query_hash call limit.

**Comment by zahra-ash0uri** [comment]
You're welcome.
As I see, it's a certain query_hash and there is no call limit but if you don't adhere time-sleep in requests, you would get "wait"  error.

**Comment by mswdevsla** [comment]
@zahra-ash0uri 
Yeah, you're right. So I'm adjusting the time-sleep for every request.
Thank you for answer 😄

**Comment by JulienMaille** [comment]
i'm getting similar error with `current_user()` endpoint `accounts/current_user/` #291 
Any clue @zahra-ash0uri ? Thanks in advance
