### ISSUE TITLE
[Question] Is there any way to avoid/deal with 'challenge required' error?

### ISSUE THREAD

**Issue by W84TheSun** [ping/instagram_private_api#27]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering are out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [ x ] Updated to the lastest version v1.3.5
- [ x ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ x ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ x ] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ x ] Question
- [ ] Other

---

### Describe your issue

Hi, @ping! Many thanks for your library it's awesome!
I want to provide some context before I'll get to the question part. I started using your library on my local machine but when I moved to VPS which is located far away from me I got this error pretty much every time:

```instagram_private_api.errors.ClientError: Bad Request: challenge_required```

I figure out that Instagram wants me to confirm login attempt or entered the security code on the login page.
So, if there any way to avoid this rather than creating the Instagram account under VPN in the country where VPS located?

Thanks for your attention!

**Comment by ping** [comment]
Sorry, I don't know of any way to avoid that in your situation. The challenge is one of Instagram's security measures, and understandably, logging in from a different country would appear to be quite suspicious to IG.
