### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by wlerin** [ping/instagram_private_api#28]
### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version v1.3.6

It's been some time since I updated the api due to minor cookiejar customisations, but it definitely still does nothing to handle [socket.timeout](https://github.com/ping/instagram_private_api/search?q=timeout), ConnectionResetError, or httplib.IncompleteRead

- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### "Bug"

Python version: 3.6.0

The "error" is uncaught exceptions thrown by the underlying urllib etc. libraries, as a result of transient network conditions, so they are not easily reproducible. Any long running script that makes repeated api calls should encounter them eventually. That said, the relevant parts of the code I have which (used to) throw them most often:

```python
from .instagram_api import (
    Client,
    ClientCookieExpiredError, ClientLoginRequiredError, ClientLoginError, ClientError,
    LiveDownloader
)
import socket  # socket.timeout
from urllib.error import URLError
from http.client import IncompleteRead
# ConnectionResetError is a builtin


class InstagramClient(object):
    def __init__(self, username, password, **kwargs):
        self.api = Client(username, password, **kwargs)
        self.api.cookie_jar.format = 'dict'

    # there should be a check for tray.get('status') == 'ok' here
    # i may change that after posting this
    def reels_tray(self):
        try:
            tray = self.api.reels_tray()
        except socket.timeout:
            return {
                "tray": [],
                "broadcasts": []
            }
        else:
            return tray

    def reels_broadcasts(self):
        tray = self.reels_tray()
        for bc in tray.get('broadcasts', ()):
            yield bc

class InstagramLiveWatcher:
    def __init__(self, client):
        self.client = client

    def get_broadcasts(self):
        try:
            yield from self.client.reels_broadcasts()
        except ClientError as e:
            print('Client Error: {} {}\n{}'.format(e.code, e, e.error_response))
            yield from ()
        except URLError as e:
            print('URL Error: {}'.format(e))
            yield from ()
        except IncompleteRead as e:
            print('Incomplete Read: {}'.format(e))
            yield from ()
        except ConnectionResetError as e:
            print('Connection Reset Error: {}'.format(e))
            yield from ()
```

I've also had to rewrite some methods from the LiveDownloader extension to handle errors there without crashing the thread, but that's not strictly related to this project.

Error/Debug Log:

```python
Exception in thread InstagramLiveWatcher:
Traceback (most recent call last):
  File "/home/wlerin/.local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/wlerin/.local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/live_watcher.py", line 297, in run
    for broadcast in self.get_broadcasts():
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/live_watcher.py", line 277, in get_broadcasts
    yield from self.client.reels_broadcasts()
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/client.py", line 175, in reels_broadcasts
    tray = self.reels_tray()
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/client.py", line 165, in reels_tray
    tray = self.api.reels_tray()
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/instagram_api/instagram_private_api/instagram_private_api/en
dpoints/feed.py", line 96, in reels_tray
    res = self._call_api('feed/reels_tray/', query=kwargs)
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/instagram_api/instagram_private_api/instagram_private_api/cl
ient.py", line 436, in _call_api
    response_content = self._read_response(response)
  File "/home/wlerin/PycharmProjects/social48/social48/instagram/instagram_api/instagram_private_api/instagram_private_api/cl
ient.py", line 380, in _read_response
    buf = BytesIO(response.read())
  File "/home/wlerin/.local/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/home/wlerin/.local/lib/python3.6/http/client.py", line 612, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/wlerin/.local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/wlerin/.local/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/home/wlerin/.local/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/home/wlerin/.local/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

(I don't have logs from IncompleteRead or socket.timeout)

While it's entirely possible to catch these errors in the application, it would help development if the api either documented which errors might be thrown, or caught some of the more unusual ones and wrapped them (not necessarily in a monolithic ClientError). However, while it's harmless for the application to just retry communication interrupted by ConnectionResetError and IncompleteRead, they both seem like something the API knows enough to handle without raising an error.

(I'm also posting this to give an example of "handling" the error outside the api, related to issue #26 .)

----------------

And while I'm on the topic of errors, I don't see `raise Exception` in live code anymore, but there are still several places where the API is catching bare Exceptions:

[private.endpoints.accounts](https://github.com/ping/instagram_private_api/blob/ded31bd3c6edddf7bbea58f99ccebd63b3185747/instagram_private_api/endpoints/accounts.py#L155)
[private.endpoints.upload](https://github.com/ping/instagram_private_api/blob/8d93783d029ccc014bc0de7abbedae380c908fed/instagram_private_api/endpoints/upload.py#L445)
[private.client](https://github.com/ping/instagram_private_api/blob/74cfc6879ae477916b22409c1aee23680b53612a/instagram_private_api/client.py#L482)

Obviously not doing this will lead to more unexpected exceptions filtering up, which is exactly the problem I brought up above, but this isn't any good either.

------------------

And, last and least of all, it would be nice if ClientError inherited from something more specific. e.g. [requests' base exception](http://requests.readthedocs.io/en/latest/_modules/requests/exceptions/#RequestException) class inherits from IOError

**Comment by NoLogick** [comment]
You may want to consider a change of your proxy provider. This type of errors specific for the bad proxies. Of course, it's hard to handle all HTTP errors related to the connection. Basically, you can solve this problem with a very dirty hack, I mean something like that: 
~~~
res = None
for _ in range(10):
    try:
       res = do_request()
    except:
       pass
    else:
       break
if not res:
    return
~~~
I used that crutch when I had to deal with a poor quality proxies.
But you never need this with really good proxies. Because these errors are very rare.

**Comment by ping** [comment]
1. The bare exceptions you mentioned were for json parsing error, but I've switched them out to catching ValueError instead in 5990f711c2767d611e8130da10735f90ced6d063

2. For the connection error handling, I've started some preliminary work in 8ebe788306f6ba1731e07a5c550d43b4977e6240. Comments are welcomed.

3. Your point about ClientError inheriting something more specific, is there a specific reason or benefit to do so? Why is it nicer? I did not think IOError was appropriate because ClientError can be thrown for non io-related reasons, like the Login Errors, Throttled error, Cookie Expired, etc.

**Comment by wlerin** [comment]
1. Looks good. Although [this](https://github.com/ping/instagram_private_api/blob/5990f711c2767d611e8130da10735f90ced6d063/instagram_private_api/endpoints/accounts.py#L155), while it works correctly, might be confusing to someone reading the code who isn't familiar with how exceptions are scoped in Python. Specifically I mean the use of `e` as the exception variable in both the inner and outer `except` blocks. [Here](https://github.com/ping/instagram_private_api/blob/4bf2b6914216af0dded0e7f7fa288885143def72/instagram_private_api/endpoints/upload.py#L445) and [here](https://github.com/ping/instagram_private_api/blob/5990f711c2767d611e8130da10735f90ced6d063/instagram_private_api/endpoints/accounts.py#L155) as well.

2. Ah, I hadn't realised ConnectionError was new in Python 3. Unfortunately I don't have time right now to dig into it in detail. The possible refinement I see now is having different versions of ClientConnectionError for py2 and py3, with the py3 version also inheriting from ConnectionError.

3. I suppose it's an unneeded complication. Simply subclassing all of them from ClientError as you've been doing is sufficient.

**Comment by ping** [comment]
1. Fixed with 6345a80a3d696b54bb36f48d54a01466e57bb0f2

2. I was trying to catch ConnectionError but this should now be fixed in 2ff7fe47eb2562f11c07868b573290d6fdf3370a

**Comment by wlerin** [comment]
It looks like everything error I mentioned above is now wrapped up in ClientConnectionError, at least for anything that passes through `_call_api`. There's [still](https://github.com/ping/instagram_private_api/blob/6345a80a3d696b54bb36f48d54a01466e57bb0f2/instagram_private_api/endpoints/accounts.py#L146) [three](https://github.com/ping/instagram_private_api/blob/6345a80a3d696b54bb36f48d54a01466e57bb0f2/instagram_private_api/endpoints/upload.py#L436) [places](https://github.com/ping/instagram_private_api/blob/6345a80a3d696b54bb36f48d54a01466e57bb0f2/instagram_private_api/endpoints/upload.py#L590) `_call_api` is bypassed, however, in order to upload photos or videos. I don't make use of any of those methods, so I've no idea if they ever raise similar errors.

All of my concerns in this Issue have been addressed, so you can close it if you desire.

**Comment by ilkerceng** [comment]
Hi,
And thanks for such an excellent project. 
Firstly, I can't be sure if i should open a new issue or not, since the stacktrace is very similar with @wlerin'  
I got the error while getting list of followers for a user using _user_followers_ method in _private_api_. 
>   File "/usr/lib/python3.6/site-packages/instagram_private_api_extensions/pagination.py", line 48, in page
    results = fn(**args)
  File "/usr/lib/python3.6/site-packages/instagram_private_api/endpoints/friendships.py", line 56, in user_followers
    res = self._call_api(endpoint, query=query)
  File "/usr/lib/python3.6/site-packages/instagram_private_api/client.py", line 520, in _call_api
    response_content = self._read_response(response)
  File "/usr/lib/python3.6/site-packages/instagram_private_api/client.py", line 442, in _read_response
    buf = BytesIO(response.read())
  File "/usr/lib64/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/lib64/python3.6/http/client.py", line 612, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

How can i handle this error? Do you have any suggestions for this? Thanks in advance.

**Comment by ilkerceng** [comment]
@ping i was using 1.4.0, thank you so much, it gives now ClientConnectionError after upgraded to 1.4.1
