### ISSUE TITLE
Example of reusing cookies for authenticated use

### ISSUE THREAD

**Issue by andrei-polukhin** [ping/instagram_private_api#309]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---
After reading your file on reusing [cookies](https://github.com/ping/instagram_private_api/blob/master/examples/savesettings_logincallback.py), I did not find clarifying information on how to use this library with cookies. Should you add some more documentation devoted specifically to this problem?

**Comment by LinuxIsCool** [comment]
Agreed, this information would be very helpful thank you.

**Comment by 321qwedsa000** [comment]
this code may help you to reuse cookie for sure.
```py
from instagram_private_api import Client,ClientCompatPatch
import pickle
import os
def writeSettings(user,pwd,settings_file):
    api = Client(user,pwd)
    pickle.dump(api.settings,open(settings_file,"wb"))
def readSettings(settings_file):
    return pickle.load(open(settings_file,"rb"))
if not os.path.exists("settingObj"):
    writeSettings("user","pwd","settingObj")
cache_settings = readSettings("settingObj")
api = Client("user","pwd",settings=cache_settings)
```

**Comment by andrei-polukhin** [comment]
> this code may help you to reuse cookie for sure.
> 
> ```python
> from instagram_private_api import Client,ClientCompatPatch
> import pickle
> import os
> def writeSettings(user,pwd,settings_file):
>     api = Client(user,pwd)
>     pickle.dump(api.settings,open(settings_file,"wb"))
> def readSettings(settings_file):
>     return pickle.load(open(settings_file,"rb"))
> if not os.path.exists("settingObj"):
>     writeSettings("user","pwd","settingObj")
> cache_settings = readSettings("settingObj")
> api = Client("user","pwd",settings=cache_settings)
> ```

Thanks!
