### ISSUE TITLE
can i add a proxy when request some data

### ISSUE THREAD

**Issue by buzai** [ping/instagram_private_api#31]
i am in chain , so there is a fuck gfw. can i add a proxy before i request data

**Comment by ping** [comment]
@buzai

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by buzai** [comment]
@ping 
No, bug, but I'd like to ask a question, do you know the firewall in China? It organized our website to visit foreign countries. So we need a proxy to visit a website abroad. I use shadowsocks. Can I use your library to access API through this agent?
