### ISSUE TITLE
user_followers method is not working

### ISSUE THREAD

**Issue by pratik-dani** [ping/instagram_private_api#319]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)

---

### Describe the Bug/Error:
I am not able to get the list of followers using user_followers error is rank_token required. Even after using generate_uuid method and passing that as a rank_token (as mentioned in the doc string) it is showing error.

---

Paste the output of ``python -V`` here:
Python 3.7.0

Code:

```python

from instagram_private_api import Client, ClientCompatPatch

user_name = #ommitted
password = #ommitted

api = Client(user_name, password)
uuid = api.generate_uuid(True)

data = api.user_followers("hermes", uuid)
```

Error/Debug Log:

```python
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

  File "<ipython-input-133-51aa45e10e36>", line 1, in <module>
    hermse = api.user_followers("devil_danii", api.generate_uuid())

  File "D:\Projects\instagram\instagram_private_api\endpoints\friendships.py", line 65, in user_followers
    res = self._call_api(endpoint, query=query_params)

  File "D:\Projects\instagram\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)

  File "D:\Projects\instagram\instagram_private_api\errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)

ClientError: Not Found
```

**Comment by burachonak** [comment]
Hi. _hermes_ is `user_name`, but you need use `user_id`.

**Comment by anuuzsoni** [comment]
> Hi. _hermes_ is `user_name`, but you need use `user_id`.

plz provide an example

**Comment by bbrewington** [comment]
@anuuzsoni you can get the user_id with the [username_info](https://github.com/ping/instagram_private_api/blob/0fda0369ac02bc03d56f5f3f99bc9de2cc25ffaa/instagram_private_api/endpoints/users.py#L22) method - here's how I would modify your example above:

```python
user_id = api.username_info('hermes')['user']['pk']
data = api.user_followers(user_id, uuid)
```
