### ISSUE TITLE
What belongd into the JSON file?

### ISSUE THREAD

**Issue by userlip** [ping/instagram_private_api#32]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hey I am sorry but I am not that familiar with python and from your code I cant really read why a JSON file has to be put in as a parameter or what even belongs into the json file 🤔 .

Hope you could clarify that for me thanks!

**Comment by ping** [comment]
The use of a json file in the examples is just a demo of how people *can* store their authenticated session info to avoid constantly relogging in. Devs can choose to store the info in a database, or any other persistant format they want. The library doesn't take in any json file parameter at all.

If you're unfamiliar with Python, this library is probably not suitable for you.
