### ISSUE TITLE
Hi, Ping, let's make Ultimate Instagram Tool!

### ISSUE THREAD

**Issue by ohld** [ping/instagram_private_api#33]
Hi, ping! Sorry about writing here in issues but I couldn't find any your contact.

My name is Daniil and I'm the head of [Instagrambot organisation](https://github.com/instagrambot). Let's work together for a big and powerful Instagram tool. Contact me if you want to unite our forces. 
https://t.me/okhlopkov
okhlopkov@phystech.edu 

Let's work together.

**Comment by ping** [comment]
@ohld

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ohld** [comment]
Still waiting for your response.

**Comment by ping** [comment]
@ohld You have already posted here before, but I'll repeat myself to be clear. I'm absolutely do not support botting and am therefore not interested.
