### ISSUE TITLE
About uploading pictures

### ISSUE THREAD

**Issue by liberty123** [ping/instagram_private_api#34]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [ yes] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ yes] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [yes ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

web_api = Client()
user_feed_info = web_api.user_feed('1234567890', count=10)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "instagram_private_api/endpoints/upload.py", line 767, in post_album
    res = self._call_api(endpoint, params=params)
  File "instagram_private_api/client.py", line 501, in _call_api
    raise ClientError(error_msg, e.code, error_response)
instagram_private_api.errors.ClientError: Bad Request: Uploaded image isn't in the right format

```

---

### Describe your issue

When I upload pictures, there is always such a mistake, I don't know what the format of the picture is

**Comment by liberty123** [comment]
I found the way, thank you

**Comment by zachschultz** [comment]
@liberty123 would you mind sharing your solution? I'm experiencing this problem

**Comment by liberty123** [comment]
@zachschultz  api.uploadAlbum(media, caption=captionText)   media is a list

**Comment by wlerin** [comment]
Maybe that's why it's called `medias` instead of `media` [(docs)](http://instagram-private-api.readthedocs.io/en/latest/api.html?highlight=upload%20album#instagram_private_api.Client.post_album)
