### ISSUE TITLE
need a little clarification from the private API: device ids and feeds.

### ISSUE THREAD

**Issue by afidegnum** [ping/instagram_private_api#35]
---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hi, 

I have come accross this app which i m very delighted to use, i extensively read the docs. I have been playing with a [parallel app ](https://github.com/LevPasha/Instagram-API-python)
However i have a little question. 
What's the recommended syntax to login with custom device ID? i have seen the one using Iphone but does it apply to android devices as well? 

From LevPasha's API,  Media are fetched from the selected Tags, along side with users who liked and other tags, what's the concise way of fetching unique media from tags, and unique users from specific tags?

**Comment by ping** [comment]
This is a library, not an app. It is meant for developers and not end users. If you have questions about another repo, direct your questions there, not here.

The device ID is a unique UUID that the lib will generate automatically. There is no need to specify a custom device ID unless there is an exceptional reason.

The docs are fairly comprehensive and and have a good search tool. The [tests/](https://github.com/ping/instagram_private_api/tree/master/tests) is also full of working usage code. I encourage devs to do their own research and experiments to fully understand how to use this lib.
