### ISSUE TITLE
Proxy usage example.

### ISSUE THREAD

**Issue by Arsi44** [ping/instagram_private_api#367]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

I-ve got problems with proxy usage. In more detail I-ve got this error (below).
I have login and password from my proxy but where should I use it?

---

Paste the output of ``python -V`` here:
Python 3.8.9

Code:

```python
from instagram_private_api import Client, ClientCompatPatch

user_name = 'username'
password = 'pwd'

api = Client(user_name, password, proxy='http://11.11.1.111:2222/')
```

Error/Debug Log:

```
Traceback (most recent call last):
  File "C:\Users\Ars44\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8912ef3d532b>", line 1, in <module>
    api = Client(user_name, password, proxy='http://45.86.3.206:7970/')
  File "C:\Users\Ars44\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 208, in __init__
    self.login()
  File "C:\Users\Ars44\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\endpoints\accounts.py", line 27, in login
    prelogin_params = self._call_api(
  File "C:\Users\Ars44\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 533, in _call_api
    raise ClientConnectionError('{} {}'.format(
instagram_private_api.errors.ClientConnectionError: URLError <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>
```

**Comment by Arsi44** [comment]
api = Client(username, password, proxy='http://username:password@ip:port')

**Comment by kkm** [comment]
> api = Client(username, password, proxy='http://username:password@ip:port')

api = Client(username, password, proxy='http://username:password@ip:port', settings=cache_settings)

I hope, its right.
