### ISSUE TITLE
Problem with Installation: "fatal: Could not read from remote repository", "error code 128 in None"...

### ISSUE THREAD

**Issue by meredithhu** [ping/instagram_private_api#38]
Could anyone kindly suggest an alternative? thanks a lot!

---

**Comment by ping** [comment]
@meredithhu

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by notcammy** [comment]
If this is your output:

```
$ pip install git+ssh://git@github.com/ping/instagram_private_api.git@1.3.6

Collecting git+ssh://git@github.com/ping/instagram_private_api.git@1.3.6
  Cloning ssh://git@github.com/ping/instagram_private_api.git (to 1.3.6) to c:\users\dirk\appdata\local\temp\pip-u6bpys-build
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q ssh://git@github.com/ping/instagram_private_api.git c:\users\dirk\appdata\local\temp\pip-u6bpys-build" failed with error code 128 in None
```

Try replacing `ssh` to `https` to clone the repository instead:

```
pip install git+https://git@github.com/ping/instagram_private_api.git@1.3.6
```

**Comment by meredithhu** [comment]
Thanks a bunch! Resolved.
