### ISSUE TITLE
No max_id showing api.user_followers

### ISSUE THREAD

**Issue by zachasman** [ping/instagram_private_api#396]
### Which client are you using?
- [ ] app (``instagram_private_api/``)

---

### Describe the Bug/Error:

I am trying to create a function that loops in the `max_id` for the `api.user_followers` function so I can extract ALL of a users followers. But I'm not seeing where to pull the `max_id` from.

---

Paste the output of ``python -V`` here:

Code:

```
from instagram_private_api import Client, ClientCompatPatch
import ssl
import json

ssl._create_default_https_context = ssl._create_unverified_context

user_name = 'XXXX'
password = 'XXXXXX'

api = Client(user_name, password)
results = api.user_followers('20769740', rank_token=api.generate_uuid())
items = results.get('items', [])
```

Shouldn't there be a token for `max_id` at the end of running `print(results)` that I can then extract and use to pull all of this users followers?

If not, how exactly would that be done?

**Comment by zachasman** [comment]
Figured it out

**Comment by Nivalam** [comment]
I have the same issue, how did you solved it ?
