### ISSUE TITLE
Retreive Top Posts of Hashtag

### ISSUE THREAD

**Issue by macdonaldcalumj** [ping/instagram_private_api#40]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

On the Instagram app when you look at the feed of a hashtag above the "Most Recent" appears 9 "Top Posts", these posts are not included with those in the "Most Recent" below.  The feed_tag() function in the app API will get the "Most Recent", but there is no way to get the "Top Posts".  Is it possible to to get these "Top Posts" either included in the feed or separately?

**Comment by ping** [comment]
It's already returned in the feed as ``'ranked_items'``.

**Comment by macdonaldcalumj** [comment]
Thanks a lot, although I feel a bit stupid now.

**Comment by chrisbuetti** [comment]
@ping is there a way to paginate through the ranked items? When putting in the next_max_id for pagination, the following response only has items, not ranked_items
