### ISSUE TITLE
How to avoiding re-login?

### ISSUE THREAD

**Issue by koddr** [ping/instagram_private_api#42]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Paste the output of ``python -V`` here: 3.5.3

---

### Describe your issue

I see in docs warning about avoiding re-login:

> You are advised to persist/cache the auth cookie details to avoid logging in every time you make an api call. Excessive logins is a surefire way to get your account flagged for removal. It's also advisable to cache the client details such as user agent, etc together with the auth details.
> 
> The saved auth cookie can be reused for up to 90 days.

But how to make that? Any example will be nice to understand! Please.

**Comment by notcammy** [comment]
There is an example in the Examples folder

https://github.com/ping/instagram_private_api/blob/master/examples/savesettings_logincallback.py

**Comment by koddr** [comment]
@notcammy I see this, but don't understand nothing.

I use `instagram_private_api` for get my Instagram feed in Django 2.0 view, like:

``` python
# ./app/views.py

from django.conf import settings
from instagram_private_api import Client as InstagramClient, ClientError as InstagramClientError

class PageAboutView(View):
    """ About View """

    template_name = 'pages/pages_about.html'

    def get(self, request):
        # Login to Instagram account
        instagram_app_api = InstagramClient(
           settings.INSTAGRAM_USERNAME, 
           settings.INSTAGRAM_PASSWORD
        )
        # Get feed by tag
        feed = instagram_app_api.feed_tag(settings.INSTAGRAM_HASHTAG)
        ...
```

How can I get code from example to this? I have no idea...

**Comment by notcammy** [comment]
Since the login process is also being done in that example you could put the authentication with cookies example in a different file and return the `api` object to (in your case) `views.py` instead.

Simple example:

auth.py: https://gist.github.com/notcammy/92fe3d79c7cb84c7532736ee2cda8a76
views.py: https://gist.github.com/notcammy/cba7ae1146cd516c0cd9c4464260a0da

**Comment by koddr** [comment]
@notcammy oh, thanks for example!

I have this error:

``` js
ClientError Bad Request: challenge_required (Code: 400, Response: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/1590876187/yDzi1BW5CN/", "api_path": "/challenge/1590876187/yDzi1BW5CN/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"})
```

I think, my account is already locked and Instagram wants to approve by email/phone 6 digit code. But if I do this at my browser (like: copy address https://i.instagram.com/challenge/1590876187/yDzi1BW5CN/, paste to browser and enter code), I get that error again. How to fix it?

**Comment by notcammy** [comment]
I think it has to do with the location you are attempting to log in from like for instance a different country (do you run the code on a remote server?), but that's something I can't help with.

**Comment by koddr** [comment]
@notcammy yes, I try to do this from my VDS server (seems country, that my Instagram account).

Trying to do something like this on VDS:

``` python
import requests

r = requests.post('https://i.instagram.com/challenge/1590876187/yDzi1BW5CN/?securityCode=403581')
print(r)
```

But always prints `<Response [403]>`

**Comment by notcammy** [comment]
Since there's nothing I can do your best bet is to create a temporary account to work with and try to resolve the issue later. Good luck.

**Comment by koddr** [comment]
@notcammy oh, yes. Thanks for help, anyway!
