### ISSUE TITLE
IG_SIG_KEY

### ISSUE THREAD

**Issue by GianluNet** [ping/instagram_private_api#43]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Talking about instagram_private_api/instagram_private_api/constants.py
I saw the variable **IG_SIG_KEY** is used to generate the message authentication, I saw this variable changed during the various updates in these months.
Where have you tried it, how can I find it or how can I generate it myself?

**Comment by Instaerror** [comment]
https://mokhdzanifaeq.github.io/2015/09/28/extracting-instagram-signature-key-2/

**Comment by GianluNet** [comment]
Thank you, it was really helpful.
Unluckily it means the client secret used can change anytime without advice :(

**Comment by ping** [comment]
A reminder that "issues about reverse engineering is out of scope".
