### ISSUE TITLE
Typo. Block a user instead of Unblock a user

### ISSUE THREAD

**Issue by sudoguy** [ping/instagram_private_api#45]
---
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Describe your issue

Typo. Block a user instead of Unblock a user

https://github.com/ping/instagram_private_api/blob/f2fd8e05e7c3533df4041f801fdc6f5dfc798fa1/instagram_private_api/endpoints/friendships.py#L206

**Comment by ping** [comment]
@sudoguy

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ping** [comment]
Thanks, fixed.
