### ISSUE TITLE
publish on pypi

### ISSUE THREAD

**Issue by thijstriemstra** [ping/instagram_private_api#46]
Can you publish this package on pypi for easy installation and maintenance?

**Comment by ping** [comment]
@thijstriemstra

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
