### ISSUE TITLE
"user_followers" gives inconsistent answers

### ISSUE THREAD

**Issue by stefanorc** [ping/instagram_private_api#47]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

Python 3.6.0
instagram_private_api 1.3.6/1.4.0

```
from instagram_private_api import Client as Client_app
import json

app = Client_app(username='username', password='password')
profile_id = 'profile_with_more_than_7500_followers'
res = app.user_followers(profile_id)
print(json.dumps(res))

```

---

the code above doesn't output the same data, depending on the username used to log-in.

Login1:
```
{
  "users": [
   200 elements
  ],
  "big_list": true,
  "next_max_id": "AQDfEih8lalqSeBTPSvf.....",
  "page_size": 200,
  "status": "ok"
}
```
Login2:
```
{
  "users": [
   ~7500 elements
  ],
  "big_list": false,
  "page_size": 200,
  "status": "ok"
}
```
Some profile will always respond to that call with 200 elements, others with close to 7500 even if res['page_size'] == 200, without providing a "next_max_id"
Seems to me that this is server side, but maybe you know how to prevent this from happening

thanks for your help

**Comment by ping** [comment]
Unfortunately no, this is entirely controlled on the server end.
