### ISSUE TITLE
No DM

### ISSUE THREAD

**Issue by squidbobble** [ping/instagram_private_api#49]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

---

### Describe your issue
Hey, was wondering if there are any plans to add dm'ing and inboixng features along with better support for fingerprint generation and resuming from 2 factor/ challenges. I can add these in if desired. Also noticed that for some reason the pots login flow is commented out and that some preloing flow is missing such as msis request. Why's that?

**Comment by ping** [comment]
@squidbobble

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by squidbobble** [comment]
added dm'ing myself along with generation for device fingerprints based off of device presets. 
Going to add better session resuming logic and caching of data/missing requests for pre/post login flow as well tomorrow,

**Comment by ping** [comment]
- I don't intend to support any of the messaging functions at present. You're welcomed to maintain your own fork with these functions though
- Also no intention to support 2FA
- I don't know what you mean by device fingerprints
- In my experience (having used the private api for almost 2 years now), the pre/post login calls don't seem to matter, which is why I haven't focused on them

**Comment by ping** [comment]
This repo is MIT licensed. So a fork is where you can do whatever you want, including the "dm stuff" if you so wish.

People making dm or spam bots is precisely the kind of thing I don't care for or will support in any form.

**Comment by xmsid** [comment]
yeah but having the dm functions implemented into the main repo instead of a fork is better.

plus i won't use it for spamming.

**Comment by ping** [comment]
It makes no sense to have code in my repo that I will not maintain, answer questions, or support in any way.

**Comment by wlerin** [comment]
You don't even need a fork, just make another Mixin for the DM functions and patch it into the Client class.
