### ISSUE TITLE
Checking if user has joined someone else's livestream (dual live)

### ISSUE THREAD

**Issue by notcammy** [ping/instagram_private_api#50]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

I was wondering if it would be possible to add functionality to check if a certain user is currently doing a Dual-Live with another user.

**Comment by ping** [comment]
As far as I can tell, when a user joins a co-broadcast, the live broadcast is also returned via the same endpoint as if it's his/her own broadcast. The difference is that the 'broadcast_owner' is set as the other user, and the current user is listed in 'cobroadcasters' instead.

**Comment by notcammy** [comment]
Thank you for the clarification.
