### ISSUE TITLE
Can not add a post description

### ISSUE THREAD

**Issue by Maxfashko** [ping/instagram_private_api#51]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Code:

```python
# Example code that will produce the no error reported
from instagram_private_api import Client, ClientCompatPatch

def get_image_for_post(media_path):
	with open(media_path, "rb") as img:
		f = img.read()
		b = bytearray(f)
	return b

user_name = 'user'
password = 'name'

api = Client(user_name, password)
bytear = get_image_for_post('/tmp/1/2018-02-17_00:39:28320.jpg')
api.post_photo(photo_data=bytear, caption="caption_text", size=(1080, 1080))
```

---

### Describe your issue

Hey. For some time, the function of adding a description to the post has stopped working. Photo is successfully fasted, but the description is still not there. I'm not using api correctly?

**Comment by ping** [comment]
@Maxfashko

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ping** [comment]
I just tested this and it worked just fine. You may be shadow banned.

**Comment by Maxfashko** [comment]
I used several accounts and connected via VPN.

**Comment by ping** [comment]
Neither of which does not mean you're not shadow banned.

Your caption can also cause IG to shadow ban posts. Especially if you are spamming hashtags.

**Comment by Maxfashko** [comment]
How do I get around this? The matter is that I did not specify hashtags. I specified only the text

**Comment by ping** [comment]
There is no "get around". You simply have to stop whatever that you were doing that IG doesn't like.
