### ISSUE TITLE
Upcoming Instagram API changes & the future of this library

### ISSUE THREAD

**Issue by notcammy** [ping/instagram_private_api#52]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

I recently came across this article: https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/
I'm curious to know how much this will affect this library and its extension module (assuming it will) and if you will be keeping them up to date, if possible.

**Comment by ping** [comment]
This library uses the **_private_** api. That blog post is about the public developer api. There is no relevance.

**Comment by notcammy** [comment]
Ah, I thought this library was built around the public API and had functions (such as broadcast info) that simply weren't documented by Instagram. Thanks again for the clarification, and I appreciate the effort you put into this lib. It's been a huge lifesaver for me so far. 👍
