### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by sam9138i** [ping/instagram_private_api#53]
{"user":{"biography":null,"blocked_by_viewer":false,"country_block":false,"external_url":null,"external_url_linkshimmed":null,"followed_by":{"count":113},"followed_by_viewer":false,"follows":{"count":94},"follows_viewer":false,"full_name":"\ud83c\uddf9\ud83c\udded March \ud83c\uddf9\ud83c\udded","has_blocked_viewer":false,"has_requested_viewer":false,"id":"5924835852","is_private":true,"is_verified":false,"mutual_followers":null,"profile_pic_url":"https://instagram.fkul7-1.fna.fbcdn.net/vp/32e9794b3ed92658f66c8f5a9858c4a0/5B13A807/t51.2885-19/s150x150/21827150_1478213012294840_7764607749345771520_n.jpg","profile_pic_url_hd":"https://instagram.fkul7-1.fna.fbcdn.net/vp/e3bc9e436ff1ee85bab397190674ea24/5B13C97F/t51.2885-19/s320x320/21827150_1478213012294840_7764607749345771520_n.jpg","requested_by_viewer":false,"username":"marchimini","connected_fb_page":null,"media":{"nodes":[],"count":84,"page_info":{"has_next_page":true,"end_cursor":"AQCtdFo6BY-gFCH44PbIYCahLjYYJV5og15okVCf9JAh9wEP28q4peWMl1RwP39PnvAkCtVXKRL6pggXA6a6OEv5YTErs8WBXrQr1SNtkI7qcQ"}},"saved_media":{"nodes":[],"count":0,"page_info":{"has_next_page":false,"end_cursor":null}},"media_collections":{"count":0,"page_info":{"has_next_page":false,"end_cursor":null},"edges":[]}},"logging_page_id":"profilePage_5924835852","show_suggested_profiles":false,"graphql":{"user":{"biography":"","blocked_by_viewer":false,"country_block":false,"external_url":null,"external_url_linkshimmed":null,"edge_followed_by":{"count":113},"followed_by_viewer":false,"edge_follow":{"count":94},"follows_viewer":false,"full_name":"\ud83c\uddf9\ud83c\udded March \ud83c\uddf9\ud83c\udded","has_blocked_viewer":false,"has_requested_viewer":false,"id":"5924835852","is_private":true,"is_verified":false,"mutual_followers":null,"profile_pic_url":"https://instagram.fkul7-1.fna.fbcdn.net/vp/32e9794b3ed92658f66c8f5a9858c4a0/5B13A807/t51.2885-19/s150x150/21827150_1478213012294840_7764607749345771520_n.jpg","profile_pic_url_hd":"https://instagram.fkul7-1.fna.fbcdn.net/vp/e3bc9e436ff1ee85bab397190674ea24/5B13C97F/t51.2885-19/s320x320/21827150_1478213012294840_7764607749345771520_n.jpg","requested_by_viewer":false,"username":"marchimini","connected_fb_page":null,"edge_owner_to_timeline_media":{"count":84,"page_info":{"has_next_page":true,"end_cursor":"AQCtdFo6BY-gFCH44PbIYCahLjYYJV5og15okVCf9JAh9wEP28q4peWMl1RwP39PnvAkCtVXKRL6pggXA6a6OEv5YTErs8WBXrQr1SNtkI7qcQ"},"edges":[]},"edge_saved_media":{"count":0,"page_info":{"has_next_page":false,"end_cursor":null},"edges":[]},"edge_media_collections":{"count":0,"page_info":{"has_next_page":false,"end_cursor":null},"edges":[]}}}}

**Comment by sam9138i** [comment]
Can anyone help me? I need see this private account ugrent

**Comment by ping** [comment]
@sam9138i

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by sam9138i** [comment]
Sorry sir.  Actually I really don't understand at all.  This is my gf instagram private 
 profile,i had lost contract with her almost one month not1 will tell me where she go or where are her I don't have anyway can find just only the thing I know about her are from her instagram profile cause from I can't find her until now there are total 6pose at instagram but I can't see it

**Comment by ping** [comment]
This is not Instagram support.
