### ISSUE TITLE
Account Create

### ISSUE THREAD

**Issue by pytexelite** [ping/instagram_private_api#55]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---

### Describe your issue
I really want to use this API, but is there a feature for creating an account? Is it something I am not seeing? I have read all of the docs and cannot find it. I would add it myself but I would not know where to start. Thank you! This API is very in depth and looks extremely useful.

**Comment by wlerin** [comment]
It would be in `endpoints/account.py` if it existed, but it doesn't and probably never will. Unless you're trying to create a large number of accounts (something this API will never support), I can't see why you couldn't just create the account on the web first.

**Comment by ping** [comment]
@wlerin is right for all the reasons stated.
