### ISSUE TITLE
Limited viewers of a story/archived story but no pagination data

### ISSUE THREAD

**Issue by kwcheights** [ping/instagram_private_api#56]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

I'm trying to retrieve some data about stories or archived ones. The number of viewers of a story  is correctly displayed but the number of users in the "viewers" list seems to be limited at 5. Furthermore, i can't find any data about pagination (max_ids or similar) except for _"viewer_cursor": "5"._
What is this value? How can i get the full viewers list?
Thank you

**Comment by ping** [comment]
Please provide a code snippet. I can't even tell which function you're referring to.

At this point, there are well over 100 endpoints, and I cannot be expected to remember enough details for each and every one of them to know easily what you're talking about.

**Comment by kwcheights** [comment]
Sorry! @ping 
I tried different methods like:
`stories = api.user_story_feed(user_id)`
or
`archived_index = api.stories_archive()`
`if archived_index["items"]:`
`item_ids = [a['id'] for a in archived_index['items']]`
`archived_stories = api.reels_media(item_ids)`
or
the `reels_tray(**kwargs)` method 

The returned json contains only 5 viewers.
Furthermore, i noticed that when using `feed_only_me(**kwargs)`, the key "likers" is missing even tough the "like_count" says "18" (right number of likes). When the number of likes is small, eg "2", the key is there. This happens when i retrieve not-archived medias too.
Thank you

**Comment by ping** [comment]
I just added the ``story_viewers()`` endpoint in 3a2befe8906dedd34cf1ef145d4b076dfe1765b9.

This library by default doesn't modify the response from IG. If something is missing, it simply wasn't returned by IG.

**Comment by kwcheights** [comment]
thank you very much

**Comment by kwcheights** [comment]
thank you very much. you're doing an amazing work on this API.

**Comment by samirchahine** [comment]
@ping please see [this](https://github.com/ping/instagram_private_api/issues/200) issue discussing the inability of `story_viewers()` to paginate the voters list with the `max_id`
