### ISSUE TITLE
Public Web API reports incorrect media likes from compat layer.

### ISSUE THREAD

**Issue by jwaterhouse** [ping/instagram_private_api#57]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the lastest version v1.4.0
- [ x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [ x] web (``instagram_web_api/``)

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

web_api = Client(auto_patch=True)

# This post has 104 likes when last checked
media_info_web = web_api.media_info2('Bfpp5Frnbby')
media_info_web.get('likes', {}).get('count')  # Returns 0
media_info_web.get('edge_media)preview_like', {}).get('count')  # Returns 104
```

---

### Describe your issue

When getting media info through the unauthenticated web API and using auto_patch=True, the number of likes returned in the compat key 'likes' is incorrect.

The compat patch is looking under 'likes' and 'edge_liked_by', but the data is located under 'edge_media_preview_like'.

**Comment by ping** [comment]
Closed by 31755e051805ef55346614e99dac4547290b9374. Thanks.
