### ISSUE TITLE
Error while using post_video "NoVideoVersionsAfterFilteringException"

### ISSUE THREAD

**Issue by whicher** [ping/instagram_private_api#59]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the lastest version v1.4.1
- [ x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 2.7.6
Code:
Example test in https://github.com/ping/instagram_private_api/blob/master/tests/private/upload.py#L78

Error/Debug Log:
{u'status': u'ok', u'media': {u'upload_id': u'1520713767738', u'device_timestamp': u'1520713767738'}, u'message': u'medi
a_needs_reupload', u'error_title': u'sve_preprocessor_failure extra:{\'sve_input_id\': 2009475669290252, \'sve_exception
_name\': \'sve_PreprocessorFailure\', \'sve_exception_message\': "facebook::sve::GetPipelineException: exception \'NoVid
eoVersionsAfterFilteringException\' with message \'No video versions to encode after filtering\' in /var/www/flib/video/
sve/instagram/SVEInstagramPipeline.php:526\\nStack trace:\\n#0 /var/www/flib/thrift/servers/video/sve/GetPipelineService
Handler.php(649): SVEInstagramPipeline->genPipeline()\\n#1 /var/www/flib/thrift/servers/video/sve/GetPipelineServiceHand
ler.php(566): GetPipelineServiceHandler->genGetPipelineLocal()\\n#2 /var/www/flib/thrift/servers/video/sve/GetPipelineSe
rviceHandler.php(399): GetPipelineServiceHandler->genGetPipelineResponseLocal()\\n#3 /var/www/flib/thrift/servers/video/
sve/GetPipelineServiceHandler.php(77): GetPipelineServiceHandler->genPipelineImpl()\\n#4 /var/www/flib/thrift/servers/vi
deo/sve/GetPipelineServiceHandler.php(46): Closure$GetPipelineServiceHandler::getPipeline()\\n#5 (): GetPipelineServiceH
andler->genRunFunction()\\n#6 /var/www/flib/core/asio/Asio.php(171): HH\\\\Asio\\\\join()\\n#7 /var/www/flib/thrift/serv
ers/video/sve/GetPipelineServiceHandler.php(79): Asio::awaitSynchronously()\\n#8 /var/www/flib/thrift/lib/fbcode/sve/if/
get_pipeline.thrift/GetPipelineService.php(708): GetPipelineServiceHandler->getPipeline()\\n#9 /var/www/flib/thrift/core
/ThriftSyncProcessor.php(35): GetPipelineServiceSyncProcessorBase->process_getPipeline()\\n#10 /var/www/flib/thrift/serv
ers/base/ThriftServer.php(271): ThriftSyncProcessor->process()\\n#11 /var/www/flib/alite/x/controller/thrift/XThriftCont
rollerBaseTrait.php(21): ThriftServer->genHandleHTTPRequest()\\n#12 /var/www/flib/alite/x/controller/thrift/XThriftContr
ollerBaseTrait.php(46): XThriftController->genThriftResponse()\\n#13 /var/www/flib/alite/x/controller/bridges/XBridgeCon
trollerWithDesktopResponse.php(24): XThriftController->genDesktopResponse()\\n#14 /var/www/zeusgodofthunder/index.php(10
6): XWebBaseController->genResponse()\\n#15 /var/www/zeusgodofthunder/index.php(182): _gen_alite_inner_main()\\n#16 /var
/www/flib/core/asio/Asio.php(35): gen_alite_main()\\n#17 (): Closure$Asio::enterAsyncEntryPoint()\\n#18 /var/www/flib/co
re/asio/Asio.php(37): HH\\\\Asio\\\\join()\\n#19 /var/www/zeusgodofthunder/index.php(216): Asio::enterAsyncEntryPoint()\
\n#20 {main}", \'sve_exception_status_code\': 500}'}
---

### Describe your issue

Trying to use post_video method but it throws a weird error; I tried with my own mp4 video, your streamable link in the tests and even some other random videos from imgur.

**Comment by ping** [comment]
Since you did not post any code, I cannot replicate this. I ran the ``test_post_video`` and it posted fine.

**Comment by whicher** [comment]
Thanks for fast reply. There you go.

```python
import json
import os
import sys
from urllib2 import urlopen

from instagram_private_api import Client
from instagram_private_api import ClientCompatPatch


def test_post_video(username, password):
  # Reposting https://streamable.com/deltx
  video_info_res = urlopen('https://api.streamable.com/videos/deltx')
  video_info = json.loads(video_info_res.read().decode('utf8'))
  mp4_info = video_info['files']['mp4']

  video_url = ('https:' if mp4_info['url'].startswith('//') else '') + mp4_info['url']
  video_size = (mp4_info['width'], mp4_info['height'])
  thumbnail_url = ('https:' if video_info['thumbnail_url'].startswith('//') else '') + video_info['thumbnail_url']
  duration = mp4_info['duration']

  video_res = urlopen(video_url)
  video_data = video_res.read()
  thumb_res = urlopen(thumbnail_url)
  thumb_data = thumb_res.read()
  api = Client(username, password)
  results = api.post_video(video_data, video_size, duration, thumb_data, caption='<3')
  print (results)


def test_post_video2(username, password):
  sample_video = os.path.join(os.path.dirname(__file__), 'output/deltx.mp4')
  sample_video_thumbnail = os.path.join(os.path.dirname(__file__), 'output/peanut.jpg')

  with open(sample_video, 'rb') as video_fp, \
          open(sample_video_thumbnail, 'rb') as thumbnail_file:
      # 640x360, 60secs
      thumbnail_data = thumbnail_file.read()
      api = Client(username, password)
      results = api.post_video(
          video_fp, (640, 360), 60.0, thumbnail_data, caption='Hello World!', max_retry_count=15)
      print results

test_post_video(sys.argv[1], sys.argv[2])  # Throws 403 error.
test_post_video2(sys.argv[1], sys.argv[2])  # "No video versions to encode after filtering".
```

**Comment by whicher** [comment]
Should I create another issue?
