### ISSUE TITLE
web_api.user_info2 bug

### ISSUE THREAD

**Issue by 3skr0** [ping/instagram_private_api#60]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.1
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.5.2

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client, ClientCompatPatch, ClientError, ClientLoginError

web_api = Client(auto_patch=True, drop_incompat_keys=False)
feed_svc = web_api.user_info2("windows")

```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/venvpyth3/lib/python3.5/site-packages/instagram_web_api/client.py", line 316, in user_info2
    ClientCompatPatch.user(info['user'], drop_incompat_keys=self.drop_incompat_keys)
KeyError: 'user'
```

---

### Describe your issue

The simple api to get user info  do not wok anymore. It used to work a few days ago.

**Comment by ping** [comment]
Fixed in 4fda68294d510c44c3c2b96e21adb303bbea432c
