### ISSUE TITLE
api.feed_tag(): problem with the order of the results

### ISSUE THREAD

**Issue by gu-ma** [ping/instagram_private_api#62]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.4.1
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

``Python 3.6.4 :: Anaconda, Inc.``

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

api = Client(username, password, settings=cached_settings)
results = api.feed_tag('tag')
posts = results.get('items', [])
for post in posts:
    # retrieve post data
    media_type, date, username, img_url, id = extract_post_data(post)
    print(date)

```
Error/Debug Log:

NC

---

### Describe your issue

Hi, thanks for sharing this great lib and congrats for the github project as well, very neat ;). So I'm trying to get a list of posts for a certain tag using ```api.feed_tag()``` everything is working well but the list is not always ordered chronologically. I mean, it is correct but there are some wrong value poping up from time to time, see screenshot below. Is it a problem from IG API? Any workaround?

![image](https://user-images.githubusercontent.com/4388440/38270960-4cf2fd8a-3785-11e8-96e2-065f7914656d.png)

Thanks!

**Comment by ping** [comment]
This lib doesn't manipulate the IG response, so what you see is what IG returns.
You can just [key sort](https://wiki.python.org/moin/HowTo/Sorting#Key_Functions) the list of posts by date before processing instead of assuming that the posts are returned in chronological order.

**Comment by gu-ma** [comment]
Thanks for the quick reply, yes I guessed it was an issue with IG API, pretty weird... 

I tried to sort the list already but the problem is that I'm using 'next_max_id' to paginate the results so it only sort part of the results. I could also aggregate all results in a list but then how do I know when to stop? Now the exit condition for the loop is `   if date < expected_date , which is very logical, so as soon as it encounter a result with a date anterior to the date we are expecting then it stops...

Or is there a way to get all results in one json maybe?

**Comment by ping** [comment]
There is no "all results". You're constrained by how the IG app communicates with the API. If the phone app doesn't do it, this lib can't either.

I don't see why you can't continue to use the same logic to decide when to stop. Sure, you may prematurely stop paging, but the alternative is to keep paging and risk getting throttled/banned.

**Comment by wlerin** [comment]
Unfortunately instagram likes to return things in the order it thinks is best, which usually doesn't make sense to anyone else. Never assume what you get back is in chronological (or any other) order.
