### ISSUE TITLE
Is it possible to extend user followers  response fields with adding any parameter to the api.user_followers function?

### ISSUE THREAD

**Issue by ilkerceng** [ping/instagram_private_api#63]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I am able to download user followers doing this: `private_client_api.user_followers(user_id)`. The response includes about 200 followers on each call with basic follower information. But the json data describing the follower information is very basic and doesn't include fields like usertags_count or media_count etc. Is it possible to get more fields on each follower? If no, i know it is possibble to get more information with calling `private_client_api.user_info(user_id)`.

**Comment by ping** [comment]
No. If you look at a user's followers in the official app, all you get is just the basic info too.

**Comment by ilkerceng** [comment]
thank you so much @ping
