### ISSUE TITLE
TAG USER IN STORY

### ISSUE THREAD

**Issue by Max0nyM** [ping/instagram_private_api#7]
## Please follow the guide below

- Issues submitted without this template format will likely be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x ] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue
Hello, HOW CAN I TAG USERS IN STORY POST? 
Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

**Comment by ping** [comment]
That's not supported yet. PRs are welcomed.

**Comment by ping** [comment]
After thinking about it, I won't implement this because story mentions must match up with a hard text overlay which will be difficult to enforce.

Example:
![image](https://cloud.githubusercontent.com/assets/104607/24087988/4fc4cca0-0d60-11e7-9b85-f5a41a661239.png)
