### ISSUE TITLE
Add caption, hashtags and reel mentions parameters for photo stories 

### ISSUE THREAD

**Issue by Perados** [ping/instagram_private_api#73]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.5
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

It would be awesome if we could have the caption, hashtags and reel mentions parameters for stories in the `post_photo_story` function in the `instagram_private_api/endpoints/upload.py` file. Something like this: https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php, but the reel mention is missing there.

As of today, it is possible to upload a story, but without any links, mentions or hashtags.

**Comment by ping** [comment]
My stand has not changed since #7 so no.
