### ISSUE TITLE
Retreiving a List of Users Who Liked a Post

### ISSUE THREAD

**Issue by asmoaesl** [ping/instagram_private_api#75]
### Before submitting an issue, make sure you have:
- [X] Updated to the lastest version v1.5.5
- [X] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [X] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [X] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

I am trying to get a list of users who have liked a specific post. I can get the number of users, but I cannot literally get the users' IDs. This function I am looking for has been implemented in another library, [here](https://github.com/instagrambot/instabot/blob/master/examples/follow_last_user_media_likers.py#L30).

**Comment by ping** [comment]
I do not look kindly upon those who link to known spam/bot tools. Consider this a warning to refrain from doing so in the future.

Closed with 78294a8f2fd0caca1a3042dca0557e46e237f842

**Comment by asmoaesl** [comment]
@ping what are you talking about? I linked to an example in a different library that had the functionality I was talking about. This has nothing to do with the library or the tools that use it themselves.

**Comment by asmoaesl** [comment]
Well, I didn't know you'd be offended by it. You didn't have to be an asshole and just close it without answering my question. I'll go look for a library worth my time elsewhere.

**Comment by Restioson** [comment]
To be fair, it is completely 100% irrelevant as to what the tool does. The purpose of the link was only to illustrate an example of what @asmoaesl meant.

**Comment by notcammy** [comment]
@asmoaesl I'm pretty sure he implemented your request with https://github.com/ping/instagram_private_api/commit/78294a8f2fd0caca1a3042dca0557e46e237f842 as linked in his first response.

**Comment by Restioson** [comment]
Yeah. That comment got deleted like rn when they realised I guess.

**Comment by ping** [comment]
For the record, this was what OP deleted.
![gmail](https://user-images.githubusercontent.com/104607/40010395-31ddb1c6-57d7-11e8-8a9c-3e72bf865c57.png)

I don't believe it's irrelevant. It's like telling a cook with a severe peanut allergy to make something chunky "like peanut butter".

I'm allergic to spam and spammers.

The point in any case is moot, I reserve my dictator rights as repo owner to ban any reference to spam and related tools.

**Comment by ping** [comment]
I will not be apologetic about being allergic to spammers, and yes, exercising my dictator rights to ban mentions of spam tools in my repo is _exactly_ how I want things.

I am willing to be reasonable about most things, just not spam and spammers.

I'm locking this issue because I believe this discussion has run its course.
