### ISSUE TITLE
Followers Activity feed

### ISSUE THREAD

**Issue by matmello** [ping/instagram_private_api#76]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.5
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Is it possible to get followers activity feed? 
or the media a specific person have recently liked?

For example when you click "Following" in the Activity screen.

Thanks!

**Comment by ping** [comment]
If you can't see it in the app, you can't do it in this library. So no.

**Comment by notcammy** [comment]
@ping This functionality is fully available in the app,

![screenshot](https://user-images.githubusercontent.com/8366383/40355647-45f720bc-5db7-11e8-9e1c-a527b06dc856.png)

**Comment by ping** [comment]
That is the Following feed, not Followers feed.

**Comment by notcammy** [comment]
My mistake. Possible to add Following feed to the library instead? OP can then follow back followers to get their recent activity feed (if available)

**Comment by ping** [comment]
This is already available as the ``news()`` endpoint. The documentation wasn't clear on this and have been updated in 5448323a0a457fe8c9e4664e07ec33dc4441e02a and 8d10e5ff3d1a80d534dc042702ae9d47f39fc1de.
