### ISSUE TITLE
how to send comment to live ?

### ISSUE THREAD

**Issue by pishnok** [ping/instagram_private_api#8]
i get this code

 broadcast_id = str(broadcast_id)
        endpoint = 'live/%(broadcast_id)s/comment/' % {'broadcast_id': broadcast_id}
        params = {
            'live_or_vod': '1',
            'offset_to_video_start': '0',
            'comment_text': comment_text,
            'user_breadcrumb': gen_user_breadcrumb(len(comment_text)),
            'idempotence_token': self.generate_uuid(),
        }

res >
{"message": "Please update your Instagram app to continue commenting", "status": "fail"}

**Comment by ping** [comment]
Edit your issue to follow the issue template. You were clearly instructed to do so but chose to ignore it. I'll close this issue if not updated in 24 hours.

**Comment by pishnok** [comment]
hi
can't help me ? :(
