### ISSUE TITLE
client set cookie error : _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by apep-1998** [ping/instagram_private_api#88]
### Before submitting an issue, make sure you have:
- [ ] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [ ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your issue
when I set cookie to this format "name1=value1; name2=value2; name3=value3; ......"
I have gotten error 

---

Paste the output of ``python -V`` here: 3.6.6

Code:

```
        self.api = Client(self.username, self.password,
                          cookie='name1=value1; name2=value2; name3=value3; ......')
```

Error/Debug Log:

```
cookie='name1=value1; name2=value2; name3=value3; ......')
  File "/usr/lib/python3.6/site-packages/instagram_private_api/client.py", line 153, in __init__
    cookie_jar = ClientCookieJar(cookie_string=cookie_string)
  File "/usr/lib/python3.6/site-packages/instagram_private_api/http.py", line 19, in __init__
    self._cookies = compat_pickle.loads(cookie_string.encode('utf-8'))
_pickle.UnpicklingError: pickle data was truncated

```

**Comment by ping** [comment]
@apep-1998

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by ping** [comment]
The cookie arg expects a pickled string of the cookiejar from a valid client.

```python
client1 = Client('user', 'password')
pickled_cookies_str = client1.settings['cookie']
# OR pickled_cookies_str = client1.cookie_jar.dump()

# use cookies from client1
client2 = Client('user', 'password', cookie=pickled_cookies_str)
```
