### ISSUE TITLE
How to mimic the "check-point" login?

### ISSUE THREAD

**Issue by zzqxztc** [ping/instagram_private_api#91]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

I used the Proxy IP to access INS. After my IP is changed, script gave the re-login Error  " ClientError checkpoint_challenge_required ".
I use this IP to access INS by official APP on mobile phone. It also shows me "we detected an unusual login attempt ". After i verify my email or phone by enter security code, my account can be logged in.
However, i run again my script to access INS account, error message is still shown "" ClientError checkpoint_challenge_required ”.
I consider if instagram_private_api can mimic the "check-point" login? I find "https://github.com/ping/instagram_private_api/tree/master/misc/checkpoint.py", but it is OBSOLETE.

I also try Web_API  to log in INS,  script gives me message " ERROR: ClientError_web HTTPError "Bad Request"".

**Comment by ping** [comment]
This library does not support the checkpoint challenge.
