### ISSUE TITLE
how to understand Instagram app's API

### ISSUE THREAD

**Issue by apep-1998** [ping/instagram_private_api#92]
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Question/Issue:

hello
Try sniffing to understand the app's API,
But I haven't done that because I can't find any program to do it.
Now, I saw you've done that, could you help me doing it?

**Comment by ping** [comment]
"Issues about reverse engineering is out of scope and will be closed without response."
