### ISSUE TITLE
checkpoint_logged_out <- What is this?

### ISSUE THREAD

**Issue by Haydardi** [ping/instagram_private_api#93]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *NO* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Hi guys, 
Recently I'm starting to receive this error. I have searched all over the internet and I just can't figure out what it means? Have you guys experienced something similar? Can you cast some light over what this means and how to combat this?

Thanks!

---

Paste the output of ``python -V2.7`` here:

Code:

```python
# Example code that will produce the error reported
from instagram_web_api import Client

proxy = 'my proxy here'
user_agent = 'Instagram 42.0.0.19.95 Android (23/6.0.1; 640dpi; 1440x2560; ZTE; A2017U; armeabi-v7a:armeabi; qcom; en_US)'

API = Client(username, password, proxy=proxy, user_agent=user_agent)

```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "/var/www/FlaskApp/FlaskApp/routes/accounts.py", line 593, in login
    API = Client(username, password, proxy=proxy, user_agent=get_user_agent())
  File "/instagram_private_api/client.py", line 204, in __init__
    self.login(self.two_factor)
  File "/instagram_private_api/endpoints/accounts.py", line 51, in login
    'accounts/login/', params=login_params, return_response=True)
  File "/instagram_private_api/client.py", line 536, in _call_api
    ErrorHandler.process(e, error_response)
  File "/instagram_private_api/errors.py", line 137, in process
    raise ClientError(error_msg, http_error.code, error_response)
ClientError: Bad Request: checkpoint_logged_out
```

**Comment by ping** [comment]
This is just another variant of the checkpoint challenge. As far as I know, it can be triggered when IG detects suspicious activity on your account (like logging in from a different geographical location).
