### ISSUE TITLE
Can't post photo web api

### ISSUE THREAD

**Issue by deounix** [ping/instagram_private_api#94]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the lastest version v1.5.7
- [x ] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x ] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [ ] app (``instagram_private_api/``)
- [x ] web (``instagram_web_api/``)

---

### Describe your issue

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

If describing a problem or a bug, code to replicate the issue *must* be provided below.

I can't post photo with web api
---

Paste the output of ``python -V`` here:

Code: 

```python
# Example code that will produce the error reported
from instagram_web_api import Client

api = Client(username="xxxxxxxxx", password="xxxxxxxxx")

api.login()
image = file("1.jpg", 'rb').read()
api.post_photo(photo_data=image, caption="Hello world!")
```

Error/Debug Log:

```python
`TypeError: coercing to Unicode: need string or buffer, long found`
```

**Comment by ping** [comment]
@deounix

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by notcammy** [comment]
After changing `file()` to `open()` the code snippet you provided works just fine. Using Python 3.6.3.

**Comment by ping** [comment]
Your error log is clearly insufficient. Please provide a full stack trace which shows where in the code the error occured.

**Comment by deounix** [comment]
@ping This in Python v2.7.x

**Comment by ping** [comment]
@deounix I asked you for a full stack trace, not your python version.
