### ISSUE TITLE
Comment question

### ISSUE THREAD

**Issue by BoSalami** [ping/instagram_private_api#97]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Rlease read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (==> [x] *no* spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.
- Any mention of spam-like actions or spam-related tools/libs/etc is strictly **not allowed**.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)

---

### Describe your Question/Issue:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Hello,
After using this plugin to post a photo, how could I get the media id of the photo just posted and then post a comment to it?

**Comment by ping** [comment]
This is not a plugin.

The response after posting already contains the media ID.

**Comment by BoSalami** [comment]
Sorry for a stupid question but,
where is the response posted?  After the photo is posted all I see is UserWarning: This endpoint has not been fully tested.
  warnings.warn('This endpoint has not been fully tested.', UserWarning)

**Comment by ping** [comment]
``client.post_photo()`` returns a dict that contains the ID.

This is a very basic coding question. You're better off looking to other places like stackoverflow for questions like this.
