### ISSUE TITLE
ClientCheckpointRequiredError

### ISSUE THREAD

**Issue by Ziberoncheg** [ping/instagram_private_api#99]
instagram_private_api.errors.ClientCheckpointRequiredError: checkpoint_challenge_required

How to solve this problem?

**Comment by ping** [comment]
@Ziberoncheg

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]

**Comment by notcammy** [comment]
See https://github.com/ping/instagram_private_api/issues/44#issuecomment-354938425.
